$Comp.ColorValuePicker=Class.create({initialize:function(a){this.id=a;this.onValuesChanged=null;this._hueInput=$(this.id+"_Hue");this._valueInput=$(this.id+"_Brightness");this._saturationInput=$(this.id+"_Saturation");
this._redInput=$(this.id+"_Red");this._greenInput=$(this.id+"_Green");this._blueInput=$(this.id+"_Blue");this._hexInput=$(this.id+"_Hex");this._event_onHsvKeyUp=this._onHsvKeyUp.bindAsEventListener(this);
this._event_onHsvBlur=this._onHsvBlur.bindAsEventListener(this);this._event_onRgbKeyUp=this._onRgbKeyUp.bindAsEventListener(this);this._event_onRgbBlur=this._onRgbBlur.bindAsEventListener(this);this._event_onHexKeyUp=this._onHexKeyUp.bindAsEventListener(this);
Event.observe(this._hueInput,"keyup",this._event_onHsvKeyUp);Event.observe(this._valueInput,"keyup",this._event_onHsvKeyUp);Event.observe(this._saturationInput,"keyup",this._event_onHsvKeyUp);Event.observe(this._hueInput,"blur",this._event_onHsvBlur);
Event.observe(this._valueInput,"blur",this._event_onHsvBlur);Event.observe(this._saturationInput,"blur",this._event_onHsvBlur);Event.observe(this._redInput,"keyup",this._event_onRgbKeyUp);Event.observe(this._greenInput,"keyup",this._event_onRgbKeyUp);
Event.observe(this._blueInput,"keyup",this._event_onRgbKeyUp);Event.observe(this._redInput,"blur",this._event_onRgbBlur);Event.observe(this._greenInput,"blur",this._event_onRgbBlur);Event.observe(this._blueInput,"blur",this._event_onRgbBlur);
Event.observe(this._hexInput,"keyup",this._event_onHexKeyUp);this.color=new $Comp.Color();if(this._hexInput.value!=""){this.color.setHex(this._hexInput.value)}this._hexInput.value=this.color.hex;this._redInput.value=this.color.r;
this._greenInput.value=this.color.g;this._blueInput.value=this.color.b;this._hueInput.value=this.color.h;this._saturationInput.value=this.color.s;this._valueInput.value=this.color.v},_onHsvKeyUp:function(a){if(a.target.value==""){return
}this.validateHsv(a);this.setValuesFromHsv();if(this.onValuesChanged){this.onValuesChanged(this)}},_onRgbKeyUp:function(a){if(a.target.value==""){return}this.validateRgb(a);this.setValuesFromRgb();if(this.onValuesChanged){this.onValuesChanged(this)
}},_onHexKeyUp:function(a){if(a.target.value==""){return}this.validateHex(a);this.setValuesFromHex();if(this.onValuesChanged){this.onValuesChanged(this)}},_onHsvBlur:function(a){if(a.target.value==""){this.setValuesFromRgb()
}},_onRgbBlur:function(a){if(a.target.value==""){this.setValuesFromHsv()}},HexBlur:function(a){if(a.target.value==""){this.setValuesFromHsv()}},validateRgb:function(a){if(!this._keyNeedsValidation(a)){return a
}this._redInput.value=this._setValueInRange(this._redInput.value,0,255);this._greenInput.value=this._setValueInRange(this._greenInput.value,0,255);this._blueInput.value=this._setValueInRange(this._blueInput.value,0,255)
},validateHsv:function(a){if(!this._keyNeedsValidation(a)){return a}this._hueInput.value=this._setValueInRange(this._hueInput.value,0,359);this._saturationInput.value=this._setValueInRange(this._saturationInput.value,0,100);
this._valueInput.value=this._setValueInRange(this._valueInput.value,0,100)},validateHex:function(b){if(!this._keyNeedsValidation(b)){return b}var a=new String(this._hexInput.value).toUpperCase();a=a.replace(/[^A-F0-9]/g,"0");
if(a.length>6){a=a.substring(0,6)}this._hexInput.value=a},_keyNeedsValidation:function(a){if(a.keyCode==9||a.keyCode==16||a.keyCode==38||a.keyCode==29||a.keyCode==40||a.keyCode==37||(a.ctrlKey&&(a.keyCode=="c".charCodeAt()||a.keyCode=="v".charCodeAt()))){return false
}return true},_setValueInRange:function(c,b,a){if(c==""||isNaN(c)){return b}c=parseInt(c);if(c>a){return a}if(c<b){return b}return c},setValuesFromRgb:function(){this.color.setRgb(this._redInput.value,this._greenInput.value,this._blueInput.value);
this._hexInput.value=this.color.hex;this._hueInput.value=this.color.h;this._saturationInput.value=this.color.s;this._valueInput.value=this.color.v},setValuesFromHsv:function(){this.color.setHsv(this._hueInput.value,this._saturationInput.value,this._valueInput.value);
this._hexInput.value=this.color.hex;this._redInput.value=this.color.r;this._greenInput.value=this.color.g;this._blueInput.value=this.color.b},setValuesFromHex:function(){this.color.setHex(this._hexInput.value);
this._redInput.value=this.color.r;this._greenInput.value=this.color.g;this._blueInput.value=this.color.b;this._hueInput.value=this.color.h;this._saturationInput.value=this.color.s;this._valueInput.value=this.color.v
}});$Comp.ColorPicker=Class.create({initialize:function(d,b){this.id=d;this.settings={startMode:"h",startHex:"ccc",clientFilesPath:"",onValuesChanged:null};Object.extend(this.settings,b||{});$(this.id).setDimensions(this.settings);
this._hueRadio=$(this.id+"_HueRadio");this._saturationRadio=$(this.id+"_SaturationRadio");this._valueRadio=$(this.id+"_BrightnessRadio");this._redRadio=$(this.id+"_RedRadio");this._greenRadio=$(this.id+"_GreenRadio");
this._blueRadio=$(this.id+"_BlueRadio");this._hueRadio.value="h";this._saturationRadio.value="s";this._valueRadio.value="v";this._redRadio.value="r";this._greenRadio.value="g";this._blueRadio.value="b";
this._event_onRadioClicked=this._onRadioClicked.bindAsEventListener(this);Event.observe(this._hueRadio,"click",this._event_onRadioClicked);Event.observe(this._saturationRadio,"click",this._event_onRadioClicked);
Event.observe(this._valueRadio,"click",this._event_onRadioClicked);Event.observe(this._redRadio,"click",this._event_onRadioClicked);Event.observe(this._greenRadio,"click",this._event_onRadioClicked);Event.observe(this._blueRadio,"click",this._event_onRadioClicked);
this._preview=$(this.id+"_Preview");this._mapBase=$(this.id+"_ColorMap");this._mapL1=new Element("img",{src:this.settings.clientFilesPath+"blank.gif",width:256,height:256});this._mapL1.style.margin="0px";
this._mapL1.style.display="block";this._mapBase.appendChild(this._mapL1);this._mapL2=new Element("img",{src:this.settings.clientFilesPath+"blank.gif",width:256,height:256});this._mapBase.appendChild(this._mapL2);
this._mapL2.style.clear="both";this._mapL2.style.margin="-256px 0px 0px 0px";this._mapL2.setOpacity(0.5);this._mapL2.style.display="block";this._bar=$(this.id+"_ColorBar");this._barL1=new Element("img",{src:this.settings.clientFilesPath+"blank.gif",width:20,height:256});
this._barL1.style.margin="0px";this._barL1.style.display="block";this._bar.appendChild(this._barL1);this._barL2=new Element("img",{src:this.settings.clientFilesPath+"blank.gif",width:20,height:256});this._barL2.style.margin="-256px 0px 0px 0px";
this._barL2.style.display="block";this._bar.appendChild(this._barL2);this._barL3=new Element("img",{src:this.settings.clientFilesPath+"blank.gif",width:20,height:256});this._barL3.style.margin="-256px 0px 0px 0px";
this._barL3.style.backgroundColor="#ff0000";this._barL3.style.display="block";this._bar.appendChild(this._barL3);this._barL4=new Element("img",{src:this.settings.clientFilesPath+"bar-brightness.png",width:20,height:256});
this._barL4.style.margin="-256px 0px 0px 0px";this._barL4.style.display="block";this._bar.appendChild(this._barL4);this._map=new $Comp.Slider(this._mapL2,{xMaxValue:255,yMinValue:255,arrowImage:this.settings.clientFilesPath+"mappoint.gif"});
this._slider=new $Comp.Slider(this._barL4,{xMinValue:1,xMaxValue:1,yMinValue:255,arrowImage:this.settings.clientFilesPath+"rangearrows.gif"});this._cvp=new $Comp.ColorValuePicker(this.id);var c=this;this._slider.onValuesChanged=function(){c.sliderValueChanged();
if(c.settings.onValuesChanged){c.settings.onValuesChanged(c)}};this._map.onValuesChanged=function(){c.mapValueChanged();if(c.settings.onValuesChanged){c.settings.onValuesChanged(c)}};this._cvp.onValuesChanged=function(){c.textValuesChanged();
if(c.settings.onValuesChanged){c.settings.onValuesChanged(c)}};this.isLessThanIE7=false;var a=parseFloat(navigator.appVersion.split("MSIE")[1]);if((a<7)&&(document.body.filters)){this.isLessThanIE7=true
}this.setColorMode(this.settings.startMode);if(this.settings.startHex){this._cvp._hexInput.value=this.settings.startHex}this._cvp.setValuesFromHex();this.positionMapAndSliderArrows();this.updateVisuals();
this.color=null},show:function(){this._map.Arrow.style.display="";this._slider.Arrow.style.display="";this._map.setPositioningVariables();this._slider.setPositioningVariables();this.positionMapAndSliderArrows()
},hide:function(){this._map.Arrow.style.display="none";this._slider.Arrow.style.display="none"},_onRadioClicked:function(a){this.setColorMode(a.target.value)},_onWebSafeClicked:function(a){this.setColorMode(this.ColorMode)
},textValuesChanged:function(){this.positionMapAndSliderArrows();this.updateVisuals()},setColorMode:function(b){this.color=this._cvp.color;function a(d,c){d.setAlpha(c,100);c.style.backgroundColor="";c.src=d.settings.clientFilesPath+"blank.gif";
c.style.filter=""}a(this,this._mapL1);a(this,this._mapL2);a(this,this._barL1);a(this,this._barL2);a(this,this._barL3);a(this,this._barL4);this._hueRadio.checked=false;this._saturationRadio.checked=false;
this._valueRadio.checked=false;this._redRadio.checked=false;this._greenRadio.checked=false;this._blueRadio.checked=false;switch(b){case"h":this._hueRadio.checked=true;this._mapL1.style.backgroundColor="#"+this.color.hex;
this._mapL2.style.backgroundColor="transparent";this.setImg(this._mapL2,this.settings.clientFilesPath+"map-hue.png");this.setAlpha(this._mapL2,100);this.setImg(this._barL4,this.settings.clientFilesPath+"bar-hue.png");
this._map.settings.xMaxValue=100;this._map.settings.yMaxValue=100;this._slider.settings.yMaxValue=359;break;case"s":this._saturationRadio.checked=true;this.setImg(this._mapL1,this.settings.clientFilesPath+"map-saturation.png");
this.setImg(this._mapL2,this.settings.clientFilesPath+"map-saturation-overlay.png");this.setAlpha(this._mapL2,0);this.setBG(this._barL3,this.color.hex);this.setImg(this._barL4,this.settings.clientFilesPath+"bar-saturation.png");
this._map.settings.xMaxValue=359;this._map.settings.yMaxValue=100;this._slider.settings.yMaxValue=100;break;case"v":this._valueRadio.checked=true;this.setBG(this._mapL1,"000");this.setImg(this._mapL2,this.settings.clientFilesPath+"map-brightness.png");
this._barL3.style.backgroundColor="#"+this.color.hex;this.setImg(this._barL4,this.settings.clientFilesPath+"bar-brightness.png");this._map.settings.xMaxValue=359;this._map.settings.yMaxValue=100;this._slider.settings.yMaxValue=100;
break;case"r":this._redRadio.checked=true;this.setImg(this._mapL2,this.settings.clientFilesPath+"map-red-max.png");this.setImg(this._mapL1,this.settings.clientFilesPath+"map-red-min.png");this.setImg(this._barL4,this.settings.clientFilesPath+"bar-red-tl.png");
this.setImg(this._barL3,this.settings.clientFilesPath+"bar-red-tr.png");this.setImg(this._barL2,this.settings.clientFilesPath+"bar-red-br.png");this.setImg(this._barL1,this.settings.clientFilesPath+"bar-red-bl.png");
break;case"g":this._greenRadio.checked=true;this.setImg(this._mapL2,this.settings.clientFilesPath+"map-green-max.png");this.setImg(this._mapL1,this.settings.clientFilesPath+"map-green-min.png");this.setImg(this._barL4,this.settings.clientFilesPath+"bar-green-tl.png");
this.setImg(this._barL3,this.settings.clientFilesPath+"bar-green-tr.png");this.setImg(this._barL2,this.settings.clientFilesPath+"bar-green-br.png");this.setImg(this._barL1,this.settings.clientFilesPath+"bar-green-bl.png");
break;case"b":this._blueRadio.checked=true;this.setImg(this._mapL2,this.settings.clientFilesPath+"map-blue-max.png");this.setImg(this._mapL1,this.settings.clientFilesPath+"map-blue-min.png");this.setImg(this._barL4,this.settings.clientFilesPath+"bar-blue-tl.png");
this.setImg(this._barL3,this.settings.clientFilesPath+"bar-blue-tr.png");this.setImg(this._barL2,this.settings.clientFilesPath+"bar-blue-br.png");this.setImg(this._barL1,this.settings.clientFilesPath+"bar-blue-bl.png");
break;default:alert("invalid mode");break}switch(b){case"h":case"s":case"v":this._map.settings.xMinValue=1;this._map.settings.yMinValue=1;this._slider.settings.yMinValue=1;break;case"r":case"g":case"b":this._map.settings.xMinValue=0;
this._map.settings.yMinValue=0;this._slider.settings.yMinValue=0;this._map.settings.xMaxValue=255;this._map.settings.yMaxValue=255;this._slider.settings.yMaxValue=255;break}this.ColorMode=b;this.positionMapAndSliderArrows();
this.updateMapVisuals();this.updateSliderVisuals()},mapValueChanged:function(){switch(this.ColorMode){case"h":this._cvp._saturationInput.value=this._map.xValue;this._cvp._valueInput.value=100-this._map.yValue;
break;case"s":this._cvp._hueInput.value=this._map.xValue;this._cvp._valueInput.value=100-this._map.yValue;break;case"v":this._cvp._hueInput.value=this._map.xValue;this._cvp._saturationInput.value=100-this._map.yValue;
break;case"r":this._cvp._blueInput.value=this._map.xValue;this._cvp._greenInput.value=256-this._map.yValue;break;case"g":this._cvp._blueInput.value=this._map.xValue;this._cvp._redInput.value=256-this._map.yValue;
break;case"b":this._cvp._redInput.value=this._map.xValue;this._cvp._greenInput.value=256-this._map.yValue;break}switch(this.ColorMode){case"h":case"s":case"v":this._cvp.setValuesFromHsv();break;case"r":case"g":case"b":this._cvp.setValuesFromRgb();
break}this.updateVisuals()},sliderValueChanged:function(){switch(this.ColorMode){case"h":this._cvp._hueInput.value=360-this._slider.yValue;break;case"s":this._cvp._saturationInput.value=100-this._slider.yValue;
break;case"v":this._cvp._valueInput.value=100-this._slider.yValue;break;case"r":this._cvp._redInput.value=255-this._slider.yValue;break;case"g":this._cvp._greenInput.value=255-this._slider.yValue;break;
case"b":this._cvp._blueInput.value=255-this._slider.yValue;break}switch(this.ColorMode){case"h":case"s":case"v":this._cvp.setValuesFromHsv();break;case"r":case"g":case"b":this._cvp.setValuesFromRgb();break
}this.updateVisuals()},positionMapAndSliderArrows:function(){this.color=this._cvp.color;var b=0;switch(this.ColorMode){case"h":b=360-this.color.h;break;case"s":b=100-this.color.s;break;case"v":b=100-this.color.v;
break;case"r":b=255-this.color.r;break;case"g":b=255-this.color.g;break;case"b":b=255-this.color.b;break}this._slider.yValue=b;this._slider.setArrowPositionFromValues();var a=0;var c=0;switch(this.ColorMode){case"h":a=this.color.s;
c=100-this.color.v;break;case"s":a=this.color.h;c=100-this.color.v;break;case"v":a=this.color.h;c=100-this.color.s;break;case"r":a=this.color.b;c=256-this.color.g;break;case"g":a=this.color.b;c=256-this.color.r;
break;case"b":a=this.color.r;c=256-this.color.g;break}this._map.xValue=a;this._map.yValue=c;this._map.setArrowPositionFromValues()},updateVisuals:function(){this.updatePreview();this.updateMapVisuals();
this.updateSliderVisuals()},updatePreview:function(){try{this._preview.style.backgroundColor="#"+this._cvp.color.hex}catch(a){}},updateMapVisuals:function(){this.color=this._cvp.color;switch(this.ColorMode){case"h":var a=new $Comp.Color({h:this.color.h,s:100,v:100});
this.setBG(this._mapL1,a.hex);break;case"s":this.setAlpha(this._mapL2,100-this.color.s);break;case"v":this.setAlpha(this._mapL2,this.color.v);break;case"r":this.setAlpha(this._mapL2,this.color.r/256*100);
break;case"g":this.setAlpha(this._mapL2,this.color.g/256*100);break;case"b":this.setAlpha(this._mapL2,this.color.b/256*100);break}},updateSliderVisuals:function(){this.color=this._cvp.color;switch(this.ColorMode){case"h":break;
case"s":var a=new $Comp.Color({h:this.color.h,s:100,v:this.color.v});this.setBG(this._barL3,a.hex);break;case"v":var e=new $Comp.Color({h:this.color.h,s:this.color.s,v:100});this.setBG(this._barL3,e.hex);
break;case"r":case"g":case"b":var h=0;var c=0;if(this.ColorMode=="r"){h=this._cvp._blueInput.value;c=this._cvp._greenInput.value}else{if(this.ColorMode=="g"){h=this._cvp._blueInput.value;c=this._cvp._redInput.value
}else{if(this.ColorMode=="b"){h=this._cvp._redInput.value;c=this._cvp._greenInput.value}}}var b=(h/256)*100;var d=(c/256)*100;var g=((256-h)/256)*100;var f=((256-c)/256)*100;this.setAlpha(this._barL4,(d>g)?g:d);
this.setAlpha(this._barL3,(d>b)?b:d);this.setAlpha(this._barL2,(f>b)?b:f);this.setAlpha(this._barL1,(f>g)?g:f);break}},setBG:function(a,d){try{a.style.backgroundColor="#"+d}catch(b){}},setImg:function(a,b){if(b.indexOf("png")&&this.isLessThanIE7){a.pngSrc=b;
a.src=this.settings.clientFilesPath+"blank.gif";a.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+b+"');"}else{a.src=b}},setAlpha:function(b,a){if(this.isLessThanIE7){var c=b.pngSrc;
if(c!=null&&c.indexOf("map-hue")==-1){b.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+c+"') progid:DXImageTransform.Microsoft.Alpha(opacity="+a+")"}}else{b.setOpacity(a/100)}}});