$Comp.Color=function(b){var a={r:0,g:0,b:0,h:0,s:0,v:0,hex:"",setRgb:function(e,d,c){this.r=e;this.g=d;this.b=c;var f=$Comp.ColorMethods.rgbToHsv(this);this.h=f.h;this.s=f.s;this.v=f.v;this.hex=$Comp.ColorMethods.rgbToHex(this)
},setHsv:function(e,d,c){this.h=e;this.s=d;this.v=c;var f=$Comp.ColorMethods.hsvToRgb(this);this.r=f.r;this.g=f.g;this.b=f.b;this.hex=$Comp.ColorMethods.rgbToHex(f)},setHex:function(c){this.hex=c;var e=$Comp.ColorMethods.hexToRgb(this.hex);
this.r=e.r;this.g=e.g;this.b=e.b;var d=$Comp.ColorMethods.rgbToHsv(e);this.h=d.h;this.s=d.s;this.v=d.v}};if(b){if(b.hex){a.setHex(b.hex)}else{if(b.r){a.setRgb(b.r,b.g,b.b)}else{if(b.h){a.setHsv(b.h,b.s,b.v)
}}}}return a};$Comp.ColorMethods={hexToRgb:function(e){e=this.validateHex(e);var d="00",c="00",a="00";if(e.length==6){d=e.substring(0,2);c=e.substring(2,4);a=e.substring(4,6)}else{if(e.length>4){d=e.substring(4,e.length);
e=e.substring(0,4)}if(e.length>2){c=e.substring(2,e.length);e=e.substring(0,2)}if(e.length>0){a=e.substring(0,e.length)}}return{r:this.hexToInt(d),g:this.hexToInt(c),b:this.hexToInt(a)}},validateHex:function(a){a=new String(a).toUpperCase();
a=a.replace(/[^A-F0-9]/g,"0");if(a.length>6){a=a.substring(0,6)}return a},webSafeDec:function(a){a=Math.round(a/51);a*=51;return a},hexToWebSafe:function(e){var d,c,a;if(e.length==3){d=e.substring(0,1);
c=e.substring(1,1);a=e.substring(2,1)}else{d=e.substring(0,2);c=e.substring(2,4);a=e.substring(4,6)}return intToHex(this.webSafeDec(this.hexToInt(d)))+this.intToHex(this.webSafeDec(this.hexToInt(c)))+this.intToHex(this.webSafeDec(this.hexToInt(a)))
},rgbToWebSafe:function(a){return{r:this.webSafeDec(a.r),g:this.webSafeDec(a.g),b:this.webSafeDec(a.b)}},rgbToHex:function(a){return this.intToHex(a.r)+this.intToHex(a.g)+this.intToHex(a.b)},intToHex:function(b){var a=(parseInt(b).toString(16));
if(a.length==1){a=("0"+a)}return a.toUpperCase()},hexToInt:function(a){return(parseInt(a,16))},rgbToHsv:function(d){var h=d.r/255;var f=d.g/255;var c=d.b/255;hsv={h:0,s:0,v:0};var e=0;var a=0;if(h>=f&&h>=c){a=h;
e=(f>c)?c:f}else{if(f>=c&&f>=h){a=f;e=(h>c)?c:h}else{a=c;e=(f>h)?h:f}}hsv.v=a;hsv.s=(a)?((a-e)/a):0;if(!hsv.s){hsv.h=0}else{delta=a-e;if(h==a){hsv.h=(f-c)/delta}else{if(f==a){hsv.h=2+(c-h)/delta}else{hsv.h=4+(h-f)/delta
}}hsv.h=parseInt(hsv.h*60);if(hsv.h<0){hsv.h+=360}}hsv.s=parseInt(hsv.s*100);hsv.v=parseInt(hsv.v*100);return hsv},hsvToRgb:function(e){rgb={r:0,g:0,b:0};var d=e.h;var l=e.s;var j=e.v;if(l==0){if(j==0){rgb.r=rgb.g=rgb.b=0
}else{rgb.r=rgb.g=rgb.b=parseInt(j*255/100)}}else{if(d==360){d=0}d/=60;l=l/100;j=j/100;var c=parseInt(d);var g=d-c;var b=j*(1-l);var a=j*(1-(l*g));var k=j*(1-(l*(1-g)));switch(c){case 0:rgb.r=j;rgb.g=k;
rgb.b=b;break;case 1:rgb.r=a;rgb.g=j;rgb.b=b;break;case 2:rgb.r=b;rgb.g=j;rgb.b=k;break;case 3:rgb.r=b;rgb.g=a;rgb.b=j;break;case 4:rgb.r=k;rgb.g=b;rgb.b=j;break;case 5:rgb.r=j;rgb.g=b;rgb.b=a;break}rgb.r=parseInt(rgb.r*255);
rgb.g=parseInt(rgb.g*255);rgb.b=parseInt(rgb.b*255)}return rgb}};