$Comp.ImageSlide=Class.create({initialize:function(b,a,c){this.options={titleHeight:35,titleOpacity:0.6,frequency:4,autoStart:true,start:0,showNextAction:true,showPreAction:true};Object.extend(this.options,c||{});
b=$(b);b.setDimensions(this.options);this.current=null;this.element=new Element("div",{className:"imageslide"});b.update(this.element);this.createMenu();var e=new Element("div",{className:"s_bar",style:"height:"+(this.options.titleHeight+25)+"px"});
e.setOpacity(this.options.titleOpacity);var g=new Element("div",{className:"s_title",style:"height:"+this.options.titleHeight+"px"}).update("Title");var f=new Element("div",{className:"s_nav"});f.observe("mouseenter",function(h){if(this.executer){this.executer.stop()
}}.bind(this)).observe("mouseleave",function(h){if(this.executer){this.executer.registerCallback()}}.bind(this));this.element.insert(e).insert(g).insert(f);this.createPreLink(f);this.slides=[];var d=0;
a.each(function(j){var h=new Element("div",{style:"display: none;width:100%;height:100%"});h.hide();h.data=j;this.element.insert(h);this.slides.push(h);var i=d++;f.insert($Comp.createLink((i+1),{className:"number"},function(k){this.showImage(i)
}.bind(this)))}.bind(this));this.createNextLink(f);this.showImage(this.options.start);if(this.options.autoStart){this.createExecuter()}},createPreLink:function(a){if(!this.options.showPreAction){return
}a.insert($Comp.createLink("&laquo;",{className:"action"},function(c){var b=this.index();if(--b<0){b=0}this.showImage(b)}.bind(this)))},createNextLink:function(a){if(!this.options.showNextAction){return
}a.insert($Comp.createLink("&raquo;",{className:"action"},function(c){var b=this.index();if(++b>=this.slides.length){b=this.slides.length-1}this.showImage(b)}.bind(this)))},showImage:function(c){if(this.exec_showImage){return
}if(this.slides[c].visible()){return}this.exec_showImage=true;var k=this.element.down(".s_nav");if(!k){return}var d=k.select(".number");var g;if(!this.current){this.current=this.slides[this.options.start];
g=true}else{var b=this.index();if(c==b){return}this.current.hide();if(b>-1){d[b].removeClassName("active")}}d[c].addClassName("active");this.current=this.slides[c];var e=this.current.data;var a=this.current.down("img");
if(!a){var a=new Element("img",{src:e.imageUrl,style:"width:100%;height:100%"});if(e.link){this.current.update($Comp.createLink(a,{href:e.link,target:"_blank",style:"width:100%;height:100%;border:0;margin:0;padding:0"}))
}else{this.current.update(a)}}var h=this.element.down(".s_title");if(h){h.update(e.title)}if(g){this.current.show();this.exec_showImage=false}else{this.current.$show({effects:this.options.effects,duration:0.8,afterFinish:function(){this.exec_showImage=false
}.bind(this)})}},createMenu:function(){var a=[{name:$MessageConst["ImageSlide.0"],onSelect:function(b,c){var d=$target(b).src;if(d){window.open(d)}}}];if(this.options.autoStart){a.push({separator:true});
a.push({name:$MessageConst["ImageSlide.1"],onSelect:function(b,c){this.createExecuter()}.bind(this)});a.push({name:$MessageConst["ImageSlide.2"],onSelect:function(b,c){this.stopExecuter()}.bind(this)})
}new $Comp.Menu(null,{selector:"#"+this.element.identify(),menuEvent:"contextmenu",minWidth:"100px",menuItems:a,onBeforeShow:function(d,c){if(this.options.autoStart){var b=d.getItems();b[1].setItemDisabled(this.executer!=null);
b[2].setItemDisabled(this.executer==null)}}.bind(this)})},index:function(){return this.slides.indexOf(this.current)},createExecuter:function(){this.executer=new PeriodicalExecuter(function(){var a=this.current.down("img");
if((a.readyState&&a.readyState!="complete")||!a.complete){return}var b=this.index();b++;if(b==this.slides.length){b=0}this.showImage(b)}.bind(this),this.options.frequency)},stopExecuter:function(){if(this.executer){this.executer.stop();
this.executer=null}}});