var CONTEXT_PATH,HOME_PATH,SKIN,IS_EFFECTS;var Browser={support:{canvas:!!document.createElement("canvas").getContext}};var $Actions={loc:function(a){if(typeof a!="string"||a.length==0){return}if(a.charAt(0)!="/"||a.toUpperCase().lastIndexOf(CONTEXT_PATH.toUpperCase(),0)==0){window.location=a
}else{window.location=CONTEXT_PATH+a}}};var $eval=function(o){try{if(typeof o==="function"){o()}else{if(typeof o==="string"){eval(o)}}}catch(e){alert(e.name+": "+e.message)}};document.getEvent=function(d){var b=d||window.event;
if(!b){var f=document.getEvent.caller;var a=[];while(f&&f.arguments){b=f.arguments[0];if(b&&b.constructor&&(window.Event==b.constructor||window.MouseEvent==b.constructor)){break}else{b=undefined}if(f==f.caller||a.include(f.caller)){break
}else{a.push(f=f.caller)}}}return b&&Event.extend(b).target?b:null};document.setCookie=function(d,e,b){var a="";if(b){var c=new Date();c.setTime(c.getTime()+(b*60*60*1000));a="; expires="+c.toGMTString()
}document.cookie=d+"="+encodeURIComponent(e)+a+"; path=/"};document.getCookie=function(a){var b=document.cookie.match(a+"=(.*?)(;|$)");if(b){return decodeURI(b[1])}else{return null}};var StylesheetFragment=new RegExp("<link[^>]+stylesheet[^>]*>","img");
String.prototype.stripStylesheets=function(){return this.replace(StylesheetFragment,"")};String.prototype.convertHtmlLines=function(){return this.replace(/\r/g,"<br>").replace(/\n/g,"<br>")};var HEX_ARRAY=new Array("0","1","2","3","4","5","6","7","8","9","a","b","c","d","e","f");
String.prototype.hexToString=function(){var b="";for(var a=0;a<this.length;a+=2){b+=String.fromCharCode(parseInt(this.substr(a,2),16))}return b};String.prototype.stringToHex=function(){var b="";for(var a=0;
a<this.length;a++){b+=HEX_ARRAY[this.charCodeAt(a)>>4]+HEX_ARRAY[this.charCodeAt(a)&15]}return b};Number.prototype.toFileString=function(){var a=this;if(a<0){return""}else{var b;if(a>1024*1024){b=(Math.round((a/(1024*1024))*100)/100)+"MB"
}else{if(a>1024){b=(Math.round((a/1024)*100)/100)+"KB"}else{b=a+"B"}}return b}};Array.prototype.empty=function(){return !this.length};Array.prototype.removeAt=function(b){var a=this[b];this.splice(b,1);
return a};Array.prototype.remove=function(b){var a;while((a=this.indexOf(b))!=-1){this.removeAt(a)}return b};Array.prototype.insert=function(b){var a=this.slice.call(arguments);a.shift();this.splice.apply(this,[b,0].concat(a));
return this};