var $ready=function(a){if(document.loaded){a.delay(0.1,document)}else{document.observe("dom:loaded",a)}};var $$Form=function(b){var e=$(b);if(e){return Form.Methods.serialize(e)}else{var d="",c=$$(b);for(var a=0;
a<c.length;a++){if(a>0){d+="&"}d+=Form.Methods.serialize(c[a])}return d}};(function(){Object.extend(Browser,Prototype.Browser);Object.extend(Browser,{effects:IS_EFFECTS&&!Object.isUndefined(window.Effect),WebKit419:Browser.WebKit&&!document.evaluate});
if(Browser.IE){Browser.IEVersion=parseFloat(navigator.appVersion.split(";")[1].strip().split(" ")[1]);if(Browser.IEVersion<=6){$ready(function(){try{document.execCommand("BackgroundImageCache",false,true)
}catch(b){}})}}var a=$;window.$=function(b){if(typeof b=="string"&&b.length>0&&(b[0]=="."||b[0]=="#")){var c=$$(b);return c.length>0?c[0]:undefined}else{var c;return a(b)||((c=$$(b)).length>0?c[0]:undefined)
}}})();Object.extend($Actions,{callSafely:function(b,d,f){if(!b){return}var e=typeof b=="string"?$Actions[b]:b;var a=function(){if(f&&f(e)){return}e(d)};if(e){a.defer()}else{var c=0;new PeriodicalExecuter(function(g){if(e||c++>10){g.stop();
if(e){a()}}},0.5)}},valueBinding:function(a,c){var b=function(g){var f=$(g);if(!f){var d=$$(g);if(d&&d.length>0){f=d[0]}}var e=a[g];if(f&&e){this.setValue(f,e)}}.bind(this);(function(){Object.keys(a).each(b);
$eval(c)}).delay(0.1)},setValue:function(c,b,d){c=$(c);if(!c){return}if(c.htmlEditor){if(d){if(Object.isElement(b)){c.htmlEditor.insertElement(CKEDITOR.dom.element.get(b))}else{c.htmlEditor.insertHtml(b)
}}else{c.htmlEditor.setData(b)}}else{if(c.tagName.toUpperCase()=="TEXTAREA"&&d){if(document.selection){c.focus();sel=document.selection.createRange();sel.text=b}else{if(c.selectionStart||c.selectionStart=="0"){var f=c.selectionStart;
var a=c.selectionEnd;var e=c.value;c.setValue(e.substring(0,f)+b+e.substring(a,e.length))}else{c.setValue(c.value+b)}}}else{c.setValue(b)}}},addHidden:function(a,b){if(!a||!b){return}$H(b.toQueryParams()).each(function(d){var c=a.down("#"+d.key);
if(Object.isElement(c)&&c.tagName.toUpperCase()=="INPUT"&&c.type=="hidden"){c.value=d.value}else{a.insert(new Element("INPUT",{type:"hidden",id:d.key,name:d.key,value:d.value}))}})},visibleToggle:function(a){if(Object.isString(a)){$$(a).each(function(b){b.toggle()
})}else{if(Object.isElement(a)){a.toggle()}}},readonly:function(a){if(Object.isString(a)){$$(a).each(function(b){$Actions.readonly(b)})}else{if(Object.isElement(a)){if(/input|textarea/i.test(a.tagName)){a.readOnly=true
}else{Form.getElements(a).each(function(b){$Actions.readonly(b)})}}}},disable:function(a){this._enable_disable(a)},enable:function(a){this._enable_disable(a,true)},_enable_disable:function(b,a){var c=a?"enable":"disable";
if(Object.isString(b)){$$(b).each(function(d){$Actions[c](d)})}else{if(Object.isElement(b)){if(/input|select|textarea|button/i.test(b.tagName)){b[c]()}else{Form.Methods[c](b)}}}},showError:function(h,g){if(!window.UI||!window.UI.Window||g){alert(h.title)
}else{if(!this.errWindows){this.errWindows={}}var a=600;var d=150;var b;if(this.errWindows[h.hash]){b=this.errWindows[h.hash]}else{b=this.errWindows[h.hash]=new UI.Window({minimize:false,maximize:false,width:a,height:d});
b.observe("hidden",function(){delete this.errWindows[h.hash]}.bind(this))}var f=new Element("div");var i=new Element("div",{className:"sy_error_dialog"}).insert(new Element("div",{className:"simple_toolbar et wrap_text"}).update(h.title.convertHtmlLines())).insert(f);
var e=new Element("div",{style:"float: right;"}).insert(new Element("input",{type:"button",style:"margin-right: 6px;",value:$MessageConst["Button.More"]}).observe("click",function(){if(f.down()){f.update("");
this.value=$MessageConst["Button.More"];b.setSize(a,d).adapt()}else{f.update(new Element("div",{className:"simple_toolbar1 ta"}).insert(new Element("textarea",{readonly:"readonly"}).update(h.detail)));
this.value=$MessageConst["Button.Less"];b.adapt()}b.center()})).insert(new Element("input",{type:"button",value:$MessageConst["Button.Cancel"]}).observe("click",function(){b.close()}));i.insert(new Element("div",{className:"eb"}).insert(e).insert(new Element("div",{style:"float: left"}).insert(new Element("a",{href:"#"}).update($MessageConst["Button.Location.Reload"]).observe("click",function(){location.reload()
}))));b.setHeader($MessageConst["Error.Title"]).setContent(i);b.center().observe("shown",function(){b.adapt().center().activate()}).show(true)}},observeSubmit:function(b,a){$elements(b).invoke("observe","keydown",function(d){var c=(d.which)?d.which:d.keyCode;
if(c==Event.KEY_RETURN){a(Event.element(d))}})}});window.$elements=function(a){if(Object.isString(a)){return $$(a)}else{if(Object.isArray(a)){return a}else{if(Object.isElement(a)){if(a=$(a)){var b=[];b.push(a);
return b}}}}return[]};Object.extend(Form.Element.Serializers,{textarea:function(a,b){if(Object.isUndefined(b)){if(a.htmlEditor){a.htmlEditor.updateElement()}return a.value}else{a.value=b}}});Object.extend(String.prototype,{addParameter:function(e){if(!e||e==""){return this.toString()
}var g=this.indexOf("?");var c;var f;if(g>-1){c=this.substring(0,g);f=this.substring(g+1)}else{var b=this.indexOf("=")>0;if(b){c="";f=this.toString()}else{c=this.toString();f=""}}var a=$H(f.toQueryParams());
var h=$H(e.toQueryParams());if(c.length>0){c+="?"}return c+Object.toQueryString(a.merge(h))},addSelectorParameter:function(a){var d=this.toString();if(a){if(Object.isElement(a)){d=d.addParameter($$Form(a))
}else{var c=$$(a);if(c){for(var b=0;b<c.length;b++){d=d.addParameter($$Form(c[b]))}}}}return d},makeElement:function(){var a=new Element("div");a.innerHTML=this.toString();return a.down()},camelcase:function(){var a=this.dasherize().camelize();
return a.charAt(0).toUpperCase()+a.slice(1)}});var $Comp={setBrowserTitle:function(b,a){document.title=a?document.title+" - "+b:b},createLink:function(e,c,d){c=Object.extend({href:(Browser.IEVersion&&Browser.IEVersion<=6)?"###":"javascript:void(0);"},c||{});
if(Browser.IEVersion&&Browser.IEVersion<=7){c=Object.extend(c,{hideFocus:true})}var b=new Element("a",c);if(e){b.update(e)}if(d){b.observe("click",d)}return b},addStyleSheet:function(a){var b=new Element("style",{type:"text/css",media:"screen"});
$(document.getElementsByTagName("head")[0]).insert(b);if(b.styleSheet){b.styleSheet.cssText=a}else{b.appendText(a)}return b},getPopup:function(b){var i=document.getEvent();var c;if(!i||!(c=Event.element(i))){return[0,0]
}if(window.$target){c=$target(c)}var p=c.cumulativeOffset();var f=p.top,h=p.left;f=f+c.getDimensions().height;p=c.cumulativeScrollOffset();f-=p.top,h-=p.left;var g=35;var a=document.viewport.getDimensions();
var l=a.width-g;var o=a.height-g;var n,k;if(Object.isElement(b)){b=$(b);n=b.getWidth();k=b.getHeight()}else{n=b.width;k=b.height}if(h+n>l){var j=l-n;h=j<0?2:j}if(f+k>o){var j=o-k;f=j<0?2:j}var m=document.viewport.getScrollOffsets();
f+=m.top;h+=m.left;return[h,f]},imageToggle:function(d,f,i){if(!(d=$(d))){return}if(!(f=$(f))){f=d.up().next()}var a=d.src;if(!a){return}d.setStyle("cursor:pointer;border:0px");i=Object.extend({cookie:true,open:true,onShow:Prototype.emptyFunction,onHide:Prototype.emptyFunction},i);
var b=a.lastIndexOf("/")+1;var h=a.substring(0,b);var c=a.substring(b);var e=function(){if(f.visible()){if(!c.startsWith("p_")){c="p_"+c}}else{if(c.startsWith("p_")){c=c.substring(2)}}d.src=h+c;if(i.cookie){document.setCookie("toggle_"+d.identify(),f.visible())
}};if(i.cookie){var g=document.getCookie("toggle_"+d.identify());if(g=="true"){f.show()}else{if(g=="false"){f.hide()}else{if(i.open){f.show()}else{f.hide()}}}}d.observe("click",function(){if(f.visible()){f.$hide2({afterFinish:function(){if(i.onHide){i.onHide()
}e()}})}else{f.$show2({afterFinish:function(){if(i.onShow){i.onShow()}e()}})}});e()},textButton:function(c,b){var a=new Element("div",{className:"text clear_float",style:"padding:0;margin:0;width:100%;"});
a.textObject=new Element("input",{type:"text",style:"width:100%;border:0px;"});if(c){a.textObject.id=a.textObject.name=c}a.buttonObject=new Element("div",{className:"textButton",style:"float: right; width: 20px; margin-top: 1px;"});
if(b){a.buttonObject.observe("click",b)}return a.insert(new Element("div",{style:"float: left; margin: 0 -20px 0 0; width: 100%;"}).insert(new Element("div",{style:"margin: 0px 20px 0 0;"}).insert(a.textObject))).insert(a.buttonObject)
},textFileButton:function(){var a=this.textButton();var c=new Element("input",{type:"file",style:"position:absolute;top:0;right:0;",hidefocus:"hidefocus",size:"1"}).setOpacity(0);c.observe("change",function(d){a.textObject.value=c.value
});a.textObject.observe("change",function(f){if(a.textObject.value==""){var d=c.up();new Element("form").insert(c).reset();d.insert(c)}});var b=new Element("div",{style:"position:relative;"}).insert(a).insert(c);
b.file=c;b.textButton=a;return b},addBackgroundTitle:function(a,d){a=$(a);if(!a){return}var e=a.getStyle("color");var b=function(){a.setValue(d);a.setStyle("color: #aaa;")};b();a.observe("focus",function(c){if($F(a)==d){a.setValue("");
a.setStyle("color:"+e)}});a.observe("blur",function(c){if($F(a)==""){b()}})},addReturnEvent:function(a,b){a.observe("keypress",function(c){if(((c.which)?c.which:c.keyCode)!=Event.KEY_RETURN){return}if(b){b(c)
}})},searchButton:function(f,b,c,e,i){if(!c){c=$MessageConst["Text.Search"]}if(!i){i=$MessageConst["Button.Search"]}var a=new Element("SPAN",{className:"sech_pane"});var d=new Element("input",{className:"txt",type:"text"});
e=parseInt(e);if(e>0){d.setStyle("width:"+e+"px")}if(c){this.addBackgroundTitle(d,c)}if(f){this.addReturnEvent(d,function(k){var j=$F(d);if(j==""||j==c){return}f(a,k)})}var h=new Element("SPAN",{className:"br"}).update(i);
if(f){h.observe("click",function(k){var j=$F(d);if(j==""||j==c){return}f(a,k)})}var g=new Element("SPAN",{className:"ar"});if(b){g.observe("click",function(j){b(a,j)})}return a.insert(d).insert(new Element("SPAN",{className:"btn"}).insert(h).insert(g))
},createTable:function(a){a=Object.extend({width:"100%",cellpadding:"0",cellspacing:"0"},a||{});return new Element("table",a).insert(new Element("tbody"))},createSplitbar:function(c,e,f){if(!(c=$(c))||!(e=$(e))){return
}var d,a,b=e.getWidth();c.observe("dblclick",function(g){e.setStyle("width: "+b+"px")});c.observe("mousedown",function(g){$(document.body).fixOnSelectStart();d=g.pointer();a=e.getWidth()});document.observe("mouseup",function(g){if(d){$(document.body).fixOnSelectStart(true);
d=null}});document.observe("mousemove",function(h){if(d){var g=a-d.x+h.pointer().x;if(g<50||g>(document.viewport.getWidth()-50)){return}e.setStyle("width: "+g+"px");$eval(f);c.fire("size:splitbar");Event.stop(h)
}})},initDragDrop:function(a,b,c){a=$(a);if(!a){return}a.select(".drag_image").each(function(d){new Draggable(d,{revert:true,scroll:window,onStart:function(){d.addClassName("drag_tooltip");if(c){d.update(c(d))
}d.drops=Droppables.drops.clone();Droppables.drops=Droppables.drops.reject(function(e){return e.hoverclass!=b})},onEnd:function(){d.removeClassName("drag_tooltip");d.update("");Droppables.drops=d.drops
}})})},fixMaxWidth:function(a,b){$elements(a).each(function(d){d.select("img, table").each(function(c){if(c.getWidth()>b){c.wrap(new Element("DIV",{style:"width: "+b+"px; overflow-x:auto;"}))}})})}};(function(){var d,c,g;
document.observe("mousedown",b);function b(j){var h=j.findElement('[draggable="true"]');if(!h){return}var i=j.element();if(i&&i.tagName=="DIV"){j.stop();c=h;d=j.pointer();if(document.body.setCapture){document.body.setCapture()
}document.observe("mousemove",e).observe("mouseup",a)}}function e(h){h.stop();if(g){f("drag:updated",h)}else{g=true;f("drag:started",h)}}function a(h){if(document.body.releaseCapture){document.body.releaseCapture()
}document.stopObserving("mousemove",e).stopObserving("mouseup",a);if(g){g=false;f("drag:ended",h)}}function f(h,j){var i=j.pointer();c.fire(h,{dx:i.x-d.x,dy:i.y-d.y,mouseEvent:j})}document.observe("keydown",function(j){var i=(j.which)?j.which:j.keyCode;
if(j.ctrlKey&&i==Event.KEY_RETURN){var h=$$("input[key=ctrlReturn]");if(h&&h.length>0){h[0].click()}}})})();Element.addMethods({getScrollDimensions:function(a){return{width:a.scrollWidth,height:a.scrollHeight}
},setDimensions:function(c){var d,a;var b=arguments[1];if(typeof b=="object"){d=b.height;a=b.width}else{d=b;a=arguments[2]}var e=function(f){return Object.isNumber(f)?f+"px":(Object.isString(f)?(f.strip().endsWith("%")?f:parseInt(f)+"px"):"auto")
};c.setStyle({height:e(d),width:e(a)})},getScrollOffsets:function(a){return Element._returnOffset(a.scrollLeft,a.scrollTop)},setScrollOffsets:function(a,b){if(arguments.length==3){b={left:b,top:arguments[2]}
}a.scrollLeft=b.left;a.scrollTop=b.top;return a},appendText:function(a,b){b=String.interpret(b);a.appendChild(document.createTextNode(b));return a},createDrag:function(c){c.enableDrag();var b=0,a=0;c.observe("drag:started",function(d){b=parseInt(c.style.top);
a=parseInt(c.style.left)}).observe("drag:updated",function(d){c.style.top=b+d.memo.dy+"px";c.style.left=a+d.memo.dx+"px"})},enableDrag:function(a){a.writeAttribute("draggable","true");return a},disableDrag:function(a){a.writeAttribute("draggable",null);
return a},isDraggable:function(a){return a.readAttribute("draggable")=="true"},fixOnSelectStart:function(b,a){if(a){if(Browser.Gecko){b.style.removeProperty("-moz-user-select")}else{b.removeAttribute("onselectstart")
}}else{if(Browser.Gecko){b.setStyle("-moz-user-select: none;")}else{b.setAttribute("onselectstart","return false;")}}},setPngBackground:function(a,c){var b=Object.extend({align:"top left",repeat:"no-repeat",sizingMethod:"scale",backgroundColor:""},arguments[2]||{});
a.setStyle((Browser.IEVersion&&Browser.IEVersion<=6)?{filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+c+"'', sizingMethod='"+b.sizingMethod+"')"}:{background:b.backgroundColor+" url("+c+") "+b.align+" "+b.repeat});
return a},observeImageLoad:function(a,b){if(a.tagName!=="IMG"){return}a.onreadystatechange=a.onload=function(){var c=a.readyState;if(b&&((c&&(c=="complete"||c=="loaded"))||a.complete==true)){b()}}},clearImageLoad:function(a){a.onreadystatechange=a.onload=null
},$visible:function(a){while(a.tagName!="BODY"){if(!$(a).visible()){return false}a=a.parentNode}return true},$remove:function(a){a.$hide2({duration:0.3,afterFinish:function(){a.remove()}})},$insert:function(a,b){if(Object.isString(b)){}},$style:function(b,c,a){a=a||{};
if(a.effects||Browser.effects){new Effect.Morph(b,Object.extend({duration:0.4,style:c},a))}else{b.setStyle(c);$eval(a.afterFinish)}},$show:function(b,a){if(b.visible()){return}a=a||{};if(a.effects||Browser.effects){b.appear(Object.extend({duration:0.2},a))
}else{b.show();$eval(a.afterFinish)}},$hide:function(b,a){if(!b.visible()){return}a=a||{};if(a.effects||Browser.effects){b.fade(Object.extend({duration:0.1},a))}else{b.hide();$eval(a.afterFinish)}},$toggle:function(b,a){b[b.visible()?"$hide":"$show"](a)
},$show2:function(b,a){if(b.visible()){return}a=a||{};if(a.effects||Browser.effects){b.slideDown(Object.extend({duration:0.2},a))}else{b.show();$eval(a.afterFinish)}},$hide2:function(b,a){if(!b.visible()){return
}a=a||{};if(a.effects||Browser.effects){b.blindUp(Object.extend({duration:0.2},a))}else{b.hide();$eval(a.afterFinish)}},$shake:function(b,a){a=a||{};if(a.effects||Browser.effects){var c=$win(b);if(c){c.content.setStyle("overflow: hidden;")
}b.shake(Object.extend({duration:0.5},a||{}));(function(){if(c){c.content.setStyle("overflow: auto;")}}).delay(0.6)}},$highlight:function(f,b,d){if(f.set_style){return}f.set_style=true;d=d||{};if(d.effects||Browser.effects){var a=d.afterFinish;
d.afterFinish=function(){$eval(a);f.set_style=false};var c=f.getStyle("background-color").parseColor("#FFFFFF");f.highlight(Object.extend({duration:1,startcolor:c,endcolor:b},d))}else{var e=f.getStyle("background");
f.setStyle("background: "+b);(function(){f.setStyle("background: "+(e?e:"none"));$eval(d.afterFinish);f.set_style=false}).delay(1)}},$opacity:function(b,a){a=a||{};if(a.effects||Browser.effects){new Effect.Opacity(b,Object.extend({duration:0.1,transition:Effect.Transitions.linear},a||{}))
}}});Object.extend(document.viewport,{setScrollOffsets:function(a){Element.setScrollOffsets(Prototype.Browser.WebKit?document.body:document.documentElement,a)},getScrollDimensions:function(){return Element.getScrollDimensions(Prototype.Browser.WebKit?document.body:document.documentElement)
}});(function(){var b={HTMLEvents:/^(?:load|unload|abort|error|select|change|submit|reset|focus|blur|resize|scroll)$/,MouseEvents:/^(?:click|mouse(?:down|up|over|move|out))$/};var a={pointerX:0,pointerY:0,button:0,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,bubbles:true,cancelable:true};
Event.simulate=function(h,d){var f=Object.extend(a,arguments[2]||{});var c,g=null;h=$(h);for(var e in b){if(b[e].test(d)){g=e;break}}if(!g){throw new SyntaxError("Only HTMLEvents and MouseEvents interfaces are supported")
}if(document.createEvent){c=document.createEvent(g);if(g=="HTMLEvents"){c.initEvent(d,f.bubbles,f.cancelable)}else{c.initMouseEvent(d,f.bubbles,f.cancelable,document.defaultView,f.button,f.pointerX,f.pointerY,f.pointerX,f.pointerY,f.ctrlKey,f.altKey,f.shiftKey,f.metaKey,f.button,h)
}h.dispatchEvent(c)}else{f.clientX=f.pointerX;f.clientY=f.pointerY;c=Object.extend(document.createEventObject(),f);h.fireEvent("on"+d,c)}return h};Element.addMethods({simulate:Event.simulate})})();