var Prototip={Version:"2.2.3"};Prototip.Styles={"default":{images:"default/",hideOthers:true,hideAfter:0.1,viewport:true,hook:false,border:6,borderColor:"#ddd",className:"default",hideOn:{element:"target",event:"mouseleave"},showOn:"mouseenter",radius:6,stem:{height:12,width:15}}};
var Tips={options:{paths:{images:"images/",javascript:""},zIndex:6000}};Object.extend(Prototip,{REQUIRED_Prototype:"1.7",convertVersionString:function(b){var a=b.replace(/_.*|\./g,"");a=parseInt(a+"0".times(4-a.length));
return b.indexOf("_")>-1?a-1:a},require:function(a){if(typeof window[a]=="undefined"||this.convertVersionString(window[a].Version)<this.convertVersionString(this["REQUIRED_"+a])){throw"Prototip requires "+a+" >= "+this["REQUIRED_"+a]
}},start:function(){this.require("Prototype");var a=/prototip([\w\d-_.]+)?\.js(.*)/;this.path=(($$("script[src]").find(function(b){return b.src.match(a)})||{}).src||"").replace(a,"");Tips.paths=function(b){return{images:/^(https?:\/\/|\/)/.test(b.images)?b.images:this.path+b.images,javascript:/^(https?:\/\/|\/)/.test(b.javascript)?b.javascript:this.path+b.javascript}
}.bind(this)(Tips.options.paths);if(!Browser.support.canvas){if(document.documentMode<8||document.namespaces.ns_vml){$ready(function(){var b=document.createStyleSheet();b.cssText="ns_vml\\:*{behavior:url(#default#VML)}"
})}else{document.namespaces.add("ns_vml","urn:schemas-microsoft-com:vml","#default#VML")}}Tips.initialize();Element.observe(window,"unload",this.unload)},toggleInt:function(a){return a>0?-1*a:a.abs()},unload:function(){Tips.removeAll()
}});Object.extend(Tips,function(){function a(b){if(b){b.deactivate();if(b.tooltip){b.wrapper.remove();if(Tips.fixIE){b.iframeShim.remove()}}Tips.tips=Tips.tips.without(b)}}return{tips:[],visible:[],initialize:function(){this.zIndexTop=this.zIndex
},_inverse:{left:"right",right:"left",top:"bottom",bottom:"top",middle:"middle",horizontal:"vertical",vertical:"horizontal"},_stemTranslation:{width:"horizontal",height:"vertical"},inverseStem:function(b){return !arguments[1]?b:this._inverse[b]
},fixIE:function(c){var b=(new RegExp("MSIE ([\\d.]+)")).exec(c);return b?parseFloat(b[1])<7:false}(navigator.userAgent),add:function(b){this.tips.push(b)},remove:function(f){var b,e=[];for(var c=0,d=this.tips.length;
c<d;c++){var g=this.tips[c];if(b||g.element!=$(f)){if(!g.element.parentNode){e.push(g)}}else{b=g}}a(b);for(var c=0,d=e.length;c<d;c++){a(e[c])}f.prototip=null},removeAll:function(){for(var b=0,c=this.tips.length;
b<c;b++){a(this.tips[b])}},raise:function(c){if(c!=this._highest){if(this.visible.length===0){this.zIndexTop=this.options.zIndex;for(var e=0,b=this.tips.length;e<b;e++){this.tips[e].wrapper.setStyle({zIndex:this.options.zIndex})
}}c.wrapper.setStyle({zIndex:this.zIndexTop++});this._highest=c}},addVisibile:function(b){this.removeVisible(b);this.visible.push(b)},removeVisible:function(b){this.visible=this.visible.without(b)},hideAll:function(){Tips.visible.invoke("hide")
},hook:function(k,j){k=$(k),j=$(j);var d=Object.extend({offset:{x:0,y:0},position:false},arguments[2]||{});var q=d.mouse||j.cumulativeOffset();q.left+=d.offset.x;q.top+=d.offset.y;var b=d.mouse?[0,0]:j.cumulativeScrollOffset(),g=document.viewport.getScrollOffsets(),c=d.mouse?"mouseHook":"target";
q.left+=-1*(b[0]-g[0]),q.top+=-1*(b[1]-g[1]);if(d.mouse){var e=[0,0];e.width=0;e.height=0}var f={element:k.getDimensions()},h={element:Object.clone(q)};f[c]=d.mouse?e:j.getDimensions(),h[c]=Object.clone(q);
for(var i in h){switch(d[i]){case"topRight":case"rightTop":h[i].left+=f[i].width;break;case"topMiddle":h[i].left+=f[i].width/2;break;case"rightMiddle":h[i].left+=f[i].width,h[i].top+=f[i].height/2;break;
case"bottomLeft":case"leftBottom":h[i].top+=f[i].height;break;case"bottomRight":case"rightBottom":h[i].left+=f[i].width,h[i].top+=f[i].height;break;case"bottomMiddle":h[i].left+=f[i].width/2,h[i].top+=f[i].height;
break;case"leftMiddle":h[i].top+=f[i].height/2}}q.left+=-1*(h.element.left-h[c].left);q.top+=-1*(h.element.top-h[c].top);if(d.position){k.setStyle({left:q.left+"px",top:q.top+"px"})}return q}}}());Tips.initialize();
var Tip=Class.create({initialize:function(d,f){this.element=$(d);if(!this.element){throw"Prototip: Element not available, cannot create a tooltip."}Tips.remove(this.element);var a=Object.isString(f)||Object.isElement(f);
var c=a?arguments[2]||[]:f;this.content=a?f:null;if(c.style){c=Object.extend(Object.clone(Prototip.Styles[c.style]),c)}this.options=Object.extend(Object.extend({border:0,borderColor:"#000000",radius:0,className:Tips.options.className,closeButton:Tips.options.closeButtons,delay:!c.showOn||c.showOn!="click"?0.14:false,hideAfter:false,hideOn:"mouseleave",hideOthers:false,hook:c.hook,offset:c.hook?{x:0,y:0}:{x:16,y:16},fixed:c.hook&&!c.hook.mouse?true:false,showOn:"mousemove",stem:false,style:"default",target:this.element,title:false,viewport:c.hook&&!c.hook.mouse?false:true,width:false},Prototip.Styles["default"]),c);
this.target=$(this.options.target);this.radius=this.options.radius;this.border=this.radius>this.options.border?this.radius:this.options.border;if(this.options.images){this.images=this.options.images.include("://")?this.options.images:Tips.paths.images+this.options.images
}else{this.images=Tips.paths.images+"styles/"+(this.options.style||"")+"/"}if(!this.images.endsWith("/")){this.images+="/"}if(Object.isString(this.options.stem)){this.options.stem={position:this.options.stem}
}if(this.options.stem.position){this.options.stem=Object.extend(Object.clone(Prototip.Styles[this.options.style].stem)||{},this.options.stem);this.options.stem.position=[this.options.stem.position.match(/[a-z]+/)[0].toLowerCase(),this.options.stem.position.match(/[A-Z][a-z]+/)[0].toLowerCase()];
this.options.stem.orientation=["left","right"].member(this.options.stem.position[0])?"horizontal":"vertical";this.stemInverse={horizontal:false,vertical:false}}if(this.options.hook.mouse){var e=this.options.hook.tip.match(/[a-z]+/)[0].toLowerCase();
this.mouseHook=Tips._inverse[e]+Tips._inverse[this.options.hook.tip.match(/[A-Z][a-z]+/)[0].toLowerCase()].capitalize()}this.setup();Tips.add(this);this.activate();Prototip.extend(this)},setup:function(){this.wrapper=(new Element("div",{className:"prototip"})).setStyle({zIndex:Tips.options.zIndex});
this.wrapper.hide();if(Tips.fixIE){this.iframeShim=(new Element("iframe",{className:"iframeShim",src:"javascript:false;",frameBorder:0})).setStyle({display:"none",zIndex:Tips.options.zIndex-1,opacity:0})
}this.tip=new Element("div",{className:"content"});this.title=(new Element("div",{className:"title"})).hide();if(this.options.closeButton||this.options.hideOn.element&&this.options.hideOn.element=="closeButton"){this.closeButton=(new Element("div",{className:"close"})).setPngBackground(this.images+"close.png")
}},build:function(){if(document.loaded){this._build(),this._isBuilding=true;return true}if(!this._isBuilding){$ready(this._build);return false}},_createCorner:function(g,h){var d=arguments[2]||this.options;
var i=d.radius;var f=d.border;var c={top:h.charAt(0)=="t",left:h.charAt(1)=="l"};if(Browser.support.canvas){var e=new Element("canvas",{className:"cornerCanvas"+h.capitalize(),width:f+"px",height:f+"px"});
g.insert(e);var j=e.getContext("2d");j.fillStyle=d.backgroundColor;j.arc(c.left?i:f-i,c.top?i:f-i,i,0,Math.PI*2,true);j.fill();j.fillRect(c.left?i:0,0,f-i,f);j.fillRect(0,c.top?i:0,f,f-i)}else{var b=new Element("div");
b.setStyle({width:f+"px",height:f+"px",margin:0,padding:0,display:"block",position:"relative",overflow:"hidden"});g.insert(b);var a=(new Element("ns_vml:roundrect",{fillcolor:d.backgroundColor,strokeWeight:"1px",strokeColor:d.backgroundColor,arcSize:(i/f*0.5).toFixed(2)})).setStyle({width:2*f-1+"px",height:2*f-1+"px",position:"absolute",left:(c.left?0:-1*f)+"px",top:(c.top?0:-1*f)+"px"});
b.insert(a);a.outerHTML=a.outerHTML}},_build:function(){$(document.body).insert(this.wrapper);if(Tips.fixIE){$(document.body).insert(this.iframeShim)}var i="wrapper";if(this.options.stem.position){this.stem=(new Element("div",{className:"prototip_Stem"})).setStyle({height:this.options.stem[this.options.stem.orientation=="vertical"?"height":"width"]+"px"});
var g=this.options.stem.orientation=="horizontal";this[i].insert(this.stemWrapper=(new Element("div",{className:"prototip_StemWrapper clearfix"})).insert(this.stemBox=new Element("div",{className:"prototip_StemBox clearfix"})));
this.stem.insert(this.stemImage=(new Element("div",{className:"prototip_StemImage"})).setStyle({height:this.options.stem[g?"width":"height"]+"px",width:this.options.stem[g?"height":"width"]+"px"}));if(Tips.fixIE&&!this.options.stem.position[1].toUpperCase().include("MIDDLE")){this.stemImage.setStyle({display:"inline"})
}i="stemBox"}if(this.border){var a=this.border,f;this[i].insert(this.borderFrame=(new Element("ul",{className:"borderFrame"})).insert(this.borderTop=(new Element("li",{className:"borderTop borderRow"})).setStyle("height: "+a+"px").insert((new Element("div",{className:"prototip_CornerWrapper prototip_CornerWrapperTopLeft"})).insert(new Element("div",{className:"prototip_Corner"}))).insert(f=(new Element("div",{className:"prototip_BetweenCorners"})).setStyle({height:a+"px"}).insert((new Element("div",{className:"prototip_Between"})).setStyle({margin:"0 "+a+"px",height:a+"px"}))).insert((new Element("div",{className:"prototip_CornerWrapper prototip_CornerWrapperTopRight"})).insert(new Element("div",{className:"prototip_Corner"})))).insert(this.borderMiddle=(new Element("li",{className:"borderMiddle borderRow"})).insert(this.borderCenter=(new Element("div",{className:"borderCenter"})).setStyle("padding: 0 "+a+"px"))).insert(this.borderBottom=(new Element("li",{className:"borderBottom borderRow"})).setStyle("height: "+a+"px").insert((new Element("div",{className:"prototip_CornerWrapper prototip_CornerWrapperBottomLeft"})).insert(new Element("div",{className:"prototip_Corner"}))).insert(f.cloneNode(true)).insert((new Element("div",{className:"prototip_CornerWrapper prototip_CornerWrapperBottomRight"})).insert(new Element("div",{className:"prototip_Corner"})))));
i="borderCenter";var e=this.borderFrame.select(".prototip_Corner");$w("tl tr bl br").each(function(h,b){var j=e[b];if(this.radius>0){this._createCorner(j,h,{backgroundColor:this.options.borderColor,border:a,radius:this.options.radius})
}else{j.addClassName("prototip_Fill")}j.setStyle({width:a+"px",height:a+"px"}).addClassName("prototip_Corner"+h.capitalize())}.bind(this));this.borderFrame.select(".prototip_Between",".borderMiddle",".prototip_Fill").invoke("setStyle",{backgroundColor:this.options.borderColor})
}this[i].insert(this.tooltip=(new Element("div",{className:"tooltip "+this.options.className})).insert(this.toolbar=(new Element("div",{className:"toolbar"})).insert(this.title)));if(this.options.width){var c=this.options.width;
if(Object.isNumber(c)){c+="px"}this.tooltip.setStyle("width:"+c)}if(this.stem){var d={};d[this.options.stem.orientation=="horizontal"?"top":"bottom"]=this.stem;this.wrapper.insert(d);this.positionStem()
}this.tooltip.insert(this.tip);this._update({title:this.options.title,content:this.content})},_update:function(d){var c=this.wrapper.getStyle("visibility");this.wrapper.setStyle("height:auto;width:auto;visibility:hidden").show();
if(this.border){this.borderTop.setStyle("height:0")}if(d.title){this.title.show().update(d.title);this.toolbar.show()}else{if(!this.closeButton){this.title.hide();this.toolbar.hide()}}if(Object.isElement(d.content)){d.content.show()
}if(Object.isString(d.content)||Object.isElement(d.content)){this.tip.update(d.content)}this.tooltip.setStyle({width:this.tooltip.getWidth()+"px"});this.wrapper.setStyle("visibility:visible").show();this.tooltip.show();
var e=this.tooltip.getDimensions();var b={width:e.width+"px"};var a=[this.wrapper];if(Tips.fixIE){a.push(this.iframeShim)}if(this.closeButton){this.title.show().insert({top:this.closeButton});this.toolbar.show()
}if(d.title||this.closeButton){this.toolbar.setStyle("width: 100%")}b.height=null;this.wrapper.setStyle({visibility:c});this.tip.addClassName("clearfix");if(d.title||this.closeButton){this.title.addClassName("clearfix")
}if(this.border){this.borderTop.setStyle("height:"+this.border+"px");b="width: "+(e.width+2*this.border)+"px";a.push(this.borderFrame)}a.invoke("setStyle",b);if(this.stem){this.positionStem();if(this.options.stem.orientation=="horizontal"){this.wrapper.setStyle({width:this.wrapper.getWidth()+this.options.stem.height+"px"})
}}this.wrapper.hide()},activate:function(){this.eventShow=this.showDelayed.bindAsEventListener(this);this.eventHide=this.hide.bindAsEventListener(this);if(this.options.fixed&&this.options.showOn=="mousemove"){this.options.showOn="mouseover"
}if(this.options.showOn&&this.options.showOn==this.options.hideOn){this.eventToggle=this.toggle.bindAsEventListener(this);this.element.observe(this.options.showOn,this.eventToggle)}if(this.closeButton){this.closeButton.observe("mouseover",function(d){d.setPngBackground(this.images+"close_hover.png")
}.bind(this,this.closeButton)).observe("mouseout",function(d){d.setPngBackground(this.images+"close.png")}.bind(this,this.closeButton))}var c={element:this.eventToggle?[]:[this.element],target:this.eventToggle?[]:[this.target],tip:this.eventToggle?[]:[this.wrapper],closeButton:[],none:[]};
var b=this.options.hideOn.element;this.hideElement=b||(this.options.hideOn?"element":"none");this.hideTargets=c[this.hideElement];if(!this.hideTargets&&b&&Object.isString(b)){this.hideTargets=this.tip.select(b)
}$w("show hide").each(function(e){var d=this.options[e+"On"].event||this.options[e+"On"];if(d=="mouseover"){d="mouseenter"}else{if(d=="mouseout"){d="mouseleave"}}this[e+"Action"]=d}.bind(this));if(!this.eventToggle&&this.options.showOn){this.element.observe(this.options.showOn,this.eventShow)
}if(this.hideTargets&&this.options.hideOn){this.hideTargets.invoke("observe",this.hideAction,this.eventHide)}if(!this.options.fixed&&this.options.showOn=="click"){this.eventPosition=this.position.bindAsEventListener(this);
this.element.observe("mousemove",this.eventPosition)}this.buttonEvent=this.hide.wrap(function(e,d){var f=d.findElement(".close");if(f){f.blur();d.stop();e(d)}}).bindAsEventListener(this);if(this.closeButton||this.options.hideOn&&this.options.hideOn.element==".close"){this.wrapper.observe("click",this.buttonEvent)
}if(this.options.showOn!="click"&&this.hideElement!="element"){this.eventCheckDelay=function(){this.clearTimer("show")}.bindAsEventListener(this);this.element.observe("mouseleave",this.eventCheckDelay)
}if(this.options.hideOn||this.options.hideAfter){var a=[this.element,this.wrapper];this.activityEnter=function(){Tips.raise(this);this.cancelHideAfter()}.bindAsEventListener(this);this.activityLeave=this.hideAfter.bindAsEventListener(this);
a.invoke("observe","mouseenter",this.activityEnter).invoke("observe","mouseleave",this.activityLeave)}},deactivate:function(){if(this.options.showOn&&this.options.showOn==this.options.hideOn){this.element.stopObserving(this.options.showOn,this.eventToggle)
}else{if(this.options.showOn){this.element.stopObserving(this.options.showOn,this.eventShow)}if(this.hideTargets&&this.options.hideOn&&this.hideAction&&this.eventHide){this.hideTargets.invoke("stopObserving",this.hideAction,this.eventHide)
}}if(this.eventPosition){this.element.stopObserving("mousemove",this.eventPosition)}if(this.eventCheckDelay){this.element.stopObserving("mouseout",this.eventCheckDelay)}this.wrapper.stopObserving();if(this.options.hideOn||this.options.hideAfter){this.element.stopObserving("mouseenter",this.activityEnter).stopObserving("mouseleave",this.activityLeave)
}},showDelayed:function(a){if(!this.tooltip){if(!this.build()){return}}this.position(a);if(!this.wrapper.visible()){this.clearTimer("show");this.showTimer=this.show.bind(this).delay(this.options.delay)
}},clearTimer:function(a){if(this[a+"Timer"]){clearTimeout(this[a+"Timer"])}},show:function(){if(!this.wrapper.visible()){if(Tips.fixIE){this.iframeShim.show()}if(this.options.hideOthers){Tips.hideAll()
}Tips.addVisibile(this);this.wrapper.$show({effects:this.options.effects,afterFinish:function(a){this.tooltip.show();if(this.stem){this.stem.show()}this.element.fire("prototip:shown")}.bind(this)})}},hideAfter:function(a){if(this.options.hideAfter){this.cancelHideAfter();
this.hideAfterTimer=this.hide.bind(this).delay(this.options.hideAfter)}},cancelHideAfter:function(){if(this.options.hideAfter){this.clearTimer("hideAfter")}},hide:function(){this.clearTimer("show");if(this.wrapper.visible()){this.afterHide()
}},afterHide:function(){if(Tips.fixIE){this.iframeShim.hide()}this.wrapper.$hide({effects:this.options.effects,afterFinish:function(a){(this.borderFrame||this.tooltip).show();Tips.removeVisible(this);this.element.fire("prototip:hidden")
}.bind(this)})},toggle:function(a){if(this.wrapper&&this.wrapper.visible()){this.hide(a)}else{this.showDelayed(a)}},positionStem:function(){var f=this.options.stem;var c=arguments[0]||this.stemInverse;
var e=Tips.inverseStem(f.position[0],c[f.orientation]);var d=Tips.inverseStem(f.position[1],c[Tips._inverse[f.orientation]]);var a=this.radius||0;this.stemImage.setPngBackground(this.images+e+d+".png");
if(f.orientation=="horizontal"){var b=e=="left"?f.height:0;this.stemWrapper.setStyle("left: "+b+"px;"),this.stemImage.setStyle({"float":e});this.stem.setStyle({left:0,top:d=="bottom"?"100%":d=="middle"?"50%":0,marginTop:(d=="bottom"?-1*f.width:d=="middle"?-0.5*f.width:0)+(d=="bottom"?-1*a:d=="top"?a:0)+"px"})
}else{this.stemWrapper.setStyle(e=="top"?"margin: 0; padding: "+f.height+"px 0 0 0;":"padding: 0; margin: 0 0 "+f.height+"px 0;");this.stem.setStyle(e=="top"?"top: 0; bottom: auto;":"top: auto; bottom: 0;");
this.stemImage.setStyle({margin:0,"float":d!="middle"?d:"none"});if(d=="middle"){this.stemImage.setStyle("margin: 0 auto;")}else{this.stemImage.setStyle("margin-"+d+": "+a+"px;")}if(Browser.WebKit419){if(e=="bottom"){this.stem.setStyle({position:"relative",clear:"both",top:"auto",bottom:"auto","float":"left",width:"100%",margin:-1*f.height+"px 0 0 0"});
this.stem.style.display="block"}else{this.stem.setStyle({position:"absolute","float":"none",margin:0})}}}this.stemInverse=c},position:function(f){if(!this.tooltip){if(!this.build()){return}}Tips.raise(this);
if(Tips.fixIE){var g=this.wrapper.getDimensions();if(!this.iframeShimDimensions||this.iframeShimDimensions.height!=g.height||this.iframeShimDimensions.width!=g.width){this.iframeShim.setStyle({width:g.width+"px",height:g.height+"px"})
}this.iframeShimDimensions=g}if(this.options.hook){var k,d;if(this.mouseHook){var l=document.viewport.getScrollOffsets();var e=f.fakePointer||{};var h,j=2;switch(this.mouseHook.toUpperCase()){case"LEFTTOP":case"TOPLEFT":h={x:0-j,y:0-j};
break;case"TOPMIDDLE":h={x:0,y:0-j};break;case"TOPRIGHT":case"RIGHTTOP":h={x:j,y:0-j};break;case"RIGHTMIDDLE":h={x:j,y:0};break;case"RIGHTBOTTOM":case"BOTTOMRIGHT":h={x:j,y:j};break;case"BOTTOMMIDDLE":h={x:0,y:j};
break;case"BOTTOMLEFT":case"LEFTBOTTOM":h={x:0-j,y:j};break;case"LEFTMIDDLE":h={x:0-j,y:0}}h.x+=this.options.offset.x;h.y+=this.options.offset.y;k=Object.extend({offset:h},{element:this.options.hook.tip,mouseHook:this.mouseHook,mouse:{top:e.pointerY||Event.pointerY(f)-l.top,left:e.pointerX||Event.pointerX(f)-l.left}});
d=Tips.hook(this.wrapper,this.target,k);if(this.options.viewport){var a=this.getPositionWithinViewport(d);var i=a.stemInverse;d=a.position;d.left+=i.vertical?2*Prototip.toggleInt(h.x-this.options.offset.x):0;
d.top+=i.vertical?2*Prototip.toggleInt(h.y-this.options.offset.y):0;if(this.stem&&(this.stemInverse.horizontal!=i.horizontal||this.stemInverse.vertical!=i.vertical)){this.positionStem(i)}}d={left:d.left+"px",top:d.top+"px"};
this.wrapper.setStyle(d)}else{k=Object.extend({offset:this.options.offset},{element:this.options.hook.tip,target:this.options.hook.target});d=Tips.hook(this.wrapper,this.target,Object.extend({position:true},k));
d={left:Math.max(d.left,5)+"px",top:Math.max(d.top,5)+"px"};this.wrapper.setStyle(d)}if(Tips.fixIE){this.iframeShim.setStyle(d)}}else{var m=this.target.cumulativeOffset();var e=f.fakePointer||{};var d={left:(this.options.fixed?m[0]:e.pointerX||Event.pointerX(f))+this.options.offset.x,top:(this.options.fixed?m[1]:e.pointerY||Event.pointerY(f))+this.options.offset.y};
if(!this.options.fixed&&this.element!==this.target){var c=this.element.cumulativeOffset();d.left+=-1*(c[0]-m[0]);d.top+=-1*(c[1]-m[1])}if(!this.options.fixed&&this.options.viewport){var a=this.getPositionWithinViewport(d);
var b=a.stemInverse;d=a.position;if(this.stem&&(this.stemInverse.horizontal!=i.horizontal||this.stemInverse.vertical!=i.vertical)){this.positionStem(i)}}d={left:d.left+"px",top:d.top+"px"};this.wrapper.setStyle(d);
if(Tips.fixIE){this.iframeShim.setStyle(d)}}},getPositionWithinViewport:function(h){var g=this.wrapper.getDimensions();var d=document.viewport.getScrollOffsets();var f=document.viewport.getDimensions();
var b={horizontal:false,vertical:false};var a={left:"width",top:"height"};for(var e in a){var c=a[e];if(h[e]+g[c]-d[e]>f[c]){h[e]=h[e]-(g[c]+2*this.options.offset[e=="left"?"x":"y"]);if(this.stem){b[Tips._stemTranslation[c]]=true
}}}return{position:h,stemInverse:b}}});Prototip.Methods={hold:function(a){if(a.element&&!a.element.parentNode){return true}return false},show:function(){if(!Prototip.Methods.hold(this)){Tips.raise(this);
this.cancelHideAfter();var a={};if(this.options.hook&&!this.options.hook.mouse){a.fakePointer={pointerX:0,pointerY:0}}else{var d=this.target.cumulativeOffset(),b=this.target.cumulativeScrollOffset(),c=document.viewport.getScrollOffsets();
d.left+=-1*(b[0]-c[0]);d.top+=-1*(b[1]-c[1]);a.fakePointer={pointerX:d.left,pointerY:d.top}}this.showDelayed(a);this.hideAfter()}}};Prototip.extend=function(a){a.element.prototip={},Object.extend(a.element.prototip,{show:Prototip.Methods.show.bind(a),hide:a.hide.bind(a),remove:Tips.remove.bind(Tips,a.element)})
};Prototip.start();function __prototip_actions_init(a){a.createTip=function(b,d,f,e,c){if(!b){return}$elements(b).each(function(h){if(h.prototip){return}var j=new Element("div");if(Object.isFunction(e)){e(h,j)
}d=d||a.ajaxrequest;if(d){j.update($MessageConst["$Loading.0"]);h.observe("prototip:shown",function(){var k=Object.isString(d)?$Actions[d]:d;k.container=j;k.doCallback=function(m,n,l){i.position()};k(h.getAttribute("tipParam"))
});a.ajaxrequest=d}else{if(f){j.update(f)}else{var g=h.next("tipContent")||h.next();if(g&&!g.visible()){j.update(g.innerHTML)}else{return}}}var i=new Tip(h,j,a.options[c>0?c:0]);i.wrapper.tip=i})};a.show=function(b){if(!(b=($(b)||$$(b)[0]))){return
}b.prototip.show()};a.hide=function(b){if(!(b=($(b)||$$(b)[0]))){return}b.prototip.hide()};a.target=function(b){return $(b).up(".prototip").tip.element}};