dhtmlx=function(d){for(var c in d){dhtmlx[c]=d[c]}return dhtmlx};dhtmlx.extend_api=function(f,e,h){var g=window[f];if(g){window[f]=function(b){if(b&&typeof b=="object"&&!b.tagName){var i=g.apply(this,e._init?e._init(b):arguments),d;
for(d in dhtmlx){if(e[d]){this[e[d]](dhtmlx[d])}}for(d in b){if(e[d]){this[e[d]](b[d])}else{d.indexOf("on")==0&&this.attachEvent(d,b[d])}}}else{i=g.apply(this,arguments)}e._patch&&e._patch(this);return i||this
},window[f].prototype=g.prototype,h&&dhtmlXHeir(window[f].prototype,h)}};dhtmlxAjax={get:function(e,d){var f=new dtmlXMLLoaderObject(!0);f.async=arguments.length<3;f.waitCall=d;f.loadXML(e);return f},post:function(f,e,h){var g=new dtmlXMLLoaderObject(!0);
g.async=arguments.length<4;g.waitCall=h;g.loadXML(f,!0,e);return g},getSync:function(b){return this.get(b,null,!0)},postSync:function(d,c){return this.post(d,c,null,!0)}};function dtmlXMLLoaderObject(f,e,h,g){this.xmlDoc="";
this.async=typeof h!="undefined"?h:!0;this.onloadAction=f||null;this.mainObject=e||null;this.waitCall=null;this.rSeed=g||!1;return this}dtmlXMLLoaderObject.count=0;dtmlXMLLoaderObject.prototype.waitLoadFunction=function(d){var c=!0;
return this.check=function(){if(d&&d.onloadAction!=null&&(!d.xmlDoc.readyState||d.xmlDoc.readyState==4)&&c){c=!1;dtmlXMLLoaderObject.count++;if(typeof d.onloadAction=="function"){d.onloadAction(d.mainObject,null,null,null,d)
}if(d.waitCall){d.waitCall.call(this,d),d.waitCall=null}}}};dtmlXMLLoaderObject.prototype.getXMLTopNode=function(f,e){if(this.xmlDoc.responseXML){var h=this.xmlDoc.responseXML.getElementsByTagName(f);h.length==0&&f.indexOf(":")!=-1&&(h=this.xmlDoc.responseXML.getElementsByTagName(f.split(":")[1]));
var g=h[0]}else{g=this.xmlDoc.documentElement}if(g){return this._retry=!1,g}if(!this._retry){return this._retry=!0,e=this.xmlDoc,this.loadXMLString(this.xmlDoc.responseText.replace(/^[\s]+/,""),!0),this.getXMLTopNode(f,e)
}dhtmlxError.throwError("LoadXML","Incorrect XML",[e||this.xmlDoc,this.mainObject]);return document.createElement("DIV")};dtmlXMLLoaderObject.prototype.loadXMLString=function(e,d){if(_isIE){this.xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),this.xmlDoc.async=this.async,this.xmlDoc.onreadystatechange=function(){},this.xmlDoc.loadXML(e)
}else{var f=new DOMParser;this.xmlDoc=f.parseFromString(e,"text/xml")}if(!d){if(this.onloadAction){this.onloadAction(this.mainObject,null,null,null,this)}if(this.waitCall){this.waitCall(),this.waitCall=null
}}};dtmlXMLLoaderObject.prototype.loadXML=function(f,e,h,g){this.rSeed&&(f+=(f.indexOf("?")!=-1?"&":"?")+"a_dhx_rSeed="+(new Date).valueOf());this.filePath=f;this.xmlDoc=!_isIE&&window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");
if(this.async){this.xmlDoc.onreadystatechange=new this.waitLoadFunction(this)}this.xmlDoc.open(e?"POST":"GET",f,this.async);g?(this.xmlDoc.setRequestHeader("User-Agent","dhtmlxRPC v0.1 ("+navigator.userAgent+")"),this.xmlDoc.setRequestHeader("Content-type","text/xml")):e&&this.xmlDoc.setRequestHeader("Content-type","application/x-www-form-urlencoded");
this.xmlDoc.setRequestHeader("X-Requested-With","XMLHttpRequest");this.xmlDoc.send(h);this.async||(new this.waitLoadFunction(this))()};dtmlXMLLoaderObject.prototype.destructor=function(){return this.setXSLParamValue=this.getXMLTopNode=this.xmlNodeToJSON=this.doSerialization=this.loadXMLString=this.loadXML=this.doXSLTransToString=this.doXSLTransToObject=this.doXPathOpera=this.doXPath=this.xmlDoc=this.mainObject=this.onloadAction=this.filePath=this.rSeed=this.async=this._retry=this._getAllNamedChilds=this._filterXPath=null
};dtmlXMLLoaderObject.prototype.xmlNodeToJSON=function(f){for(var e={},h=0;h<f.attributes.length;h++){e[f.attributes[h].name]=f.attributes[h].value}e._tagvalue=f.firstChild?f.firstChild.nodeValue:"";for(h=0;
h<f.childNodes.length;h++){var g=f.childNodes[h].tagName;g&&(e[g]||(e[g]=[]),e[g].push(this.xmlNodeToJSON(f.childNodes[h])))}return e};function callerFunction(d,c){return this.handler=function(a){if(!a){a=window.event
}d(a,c);return !0}}function getAbsoluteLeft(b){return getOffset(b).left}function getAbsoluteTop(b){return getOffset(b).top}function getOffsetSum(e){for(var d=0,f=0;e;){d+=parseInt(e.offsetTop),f+=parseInt(e.offsetLeft),e=e.offsetParent
}return{top:d,left:f}}function getOffsetRect(u){var t=u.getBoundingClientRect(),s=document.body,r=document.documentElement,q=window.pageYOffset||r.scrollTop||s.scrollTop,o=window.pageXOffset||r.scrollLeft||s.scrollLeft,p=r.clientTop||s.clientTop||0,n=r.clientLeft||s.clientLeft||0,m=t.top+q-p,l=t.left+o-n;
return{top:Math.round(m),left:Math.round(l)}}function getOffset(b){return b.getBoundingClientRect?getOffsetRect(b):getOffsetSum(b)}function convertStringToBoolean(b){typeof b=="string"&&(b=b.toLowerCase());
switch(b){case"1":case"true":case"yes":case"y":case 1:case !0:return !0;default:return !1}}function getUrlSymbol(b){return b.indexOf("?")!=-1?"&":"?"}function dhtmlDragAndDropObject(){if(window.dhtmlDragAndDrop){return window.dhtmlDragAndDrop
}this.dragStartObject=this.dragStartNode=this.dragNode=this.lastLanding=0;this.tempDOMM=this.tempDOMU=null;this.waitDrag=0;window.dhtmlDragAndDrop=this;return this}dhtmlDragAndDropObject.prototype.removeDraggableItem=function(b){b.onmousedown=null;
b.dragStarter=null;b.dragLanding=null};dhtmlDragAndDropObject.prototype.addDraggableItem=function(d,c){d.onmousedown=this.preCreateDragCopy;d.dragStarter=c;this.addDragLanding(d,c)};dhtmlDragAndDropObject.prototype.addDragLanding=function(d,c){d.dragLanding=c
};dhtmlDragAndDropObject.prototype.preCreateDragCopy=function(b){if(!((b||window.event)&&(b||event).button==2)){if(window.dhtmlDragAndDrop.waitDrag){return window.dhtmlDragAndDrop.waitDrag=0,document.body.onmouseup=window.dhtmlDragAndDrop.tempDOMU,document.body.onmousemove=window.dhtmlDragAndDrop.tempDOMM,!1
}window.dhtmlDragAndDrop.dragNode&&window.dhtmlDragAndDrop.stopDrag(b);window.dhtmlDragAndDrop.waitDrag=1;window.dhtmlDragAndDrop.tempDOMU=document.body.onmouseup;window.dhtmlDragAndDrop.tempDOMM=document.body.onmousemove;
window.dhtmlDragAndDrop.dragStartNode=this;window.dhtmlDragAndDrop.dragStartObject=this.dragStarter;document.body.onmouseup=window.dhtmlDragAndDrop.preCreateDragCopy;document.body.onmousemove=window.dhtmlDragAndDrop.callDrag;
window.dhtmlDragAndDrop.downtime=(new Date).valueOf();b&&b.preventDefault&&b.preventDefault();return !1}};dhtmlDragAndDropObject.prototype.callDrag=function(g){if(!g){g=window.event}dragger=window.dhtmlDragAndDrop;
if(!((new Date).valueOf()-dragger.downtime<100)){if(!dragger.dragNode){if(dragger.waitDrag){dragger.dragNode=dragger.dragStartObject._createDragNode(dragger.dragStartNode,g);if(!dragger.dragNode){return dragger.stopDrag()
}dragger.dragNode.onselectstart=function(){return !1};dragger.gldragNode=dragger.dragNode;document.body.appendChild(dragger.dragNode);document.body.onmouseup=dragger.stopDrag;dragger.waitDrag=0;dragger.dragNode.pWindow=window;
dragger.initFrameRoute()}else{return dragger.stopDrag(g,!0)}}if(dragger.dragNode.parentNode!=window.document.body&&dragger.gldragNode){var f=dragger.gldragNode;if(dragger.gldragNode.old){f=dragger.gldragNode.old
}f.parentNode.removeChild(f);var k=dragger.dragNode.pWindow;f.pWindow&&f.pWindow.dhtmlDragAndDrop.lastLanding&&f.pWindow.dhtmlDragAndDrop.lastLanding.dragLanding._dragOut(f.pWindow.dhtmlDragAndDrop.lastLanding);
if(_isIE){var i=document.createElement("Div");i.innerHTML=dragger.dragNode.outerHTML;dragger.dragNode=i.childNodes[0]}else{dragger.dragNode=dragger.dragNode.cloneNode(!0)}dragger.dragNode.pWindow=window;
dragger.gldragNode.old=dragger.dragNode;document.body.appendChild(dragger.dragNode);k.dhtmlDragAndDrop.dragNode=dragger.dragNode}dragger.dragNode.style.left=g.clientX+15+(dragger.fx?dragger.fx*-1:0)+(document.body.scrollLeft||document.documentElement.scrollLeft)+"px";
dragger.dragNode.style.top=g.clientY+3+(dragger.fy?dragger.fy*-1:0)+(document.body.scrollTop||document.documentElement.scrollTop)+"px";var h=g.srcElement?g.srcElement:g.target;dragger.checkLanding(h,g)
}};dhtmlDragAndDropObject.prototype.calculateFramePosition=function(g){if(window.name){for(var f=parent.frames[window.name].frameElement.offsetParent,k=0,i=0;f;){k+=f.offsetLeft,i+=f.offsetTop,f=f.offsetParent
}if(parent.dhtmlDragAndDrop){var h=parent.dhtmlDragAndDrop.calculateFramePosition(1);k+=h.split("_")[0]*1;i+=h.split("_")[1]*1}if(g){return k+"_"+i}else{this.fx=k}this.fy=i}return"0_0"};dhtmlDragAndDropObject.prototype.checkLanding=function(d,c){d&&d.dragLanding?(this.lastLanding&&this.lastLanding.dragLanding._dragOut(this.lastLanding),this.lastLanding=d,this.lastLanding=this.lastLanding.dragLanding._dragIn(this.lastLanding,this.dragStartNode,c.clientX,c.clientY,c),this.lastLanding_scr=_isIE?c.srcElement:c.target):d&&d.tagName!="BODY"?this.checkLanding(d.parentNode,c):(this.lastLanding&&this.lastLanding.dragLanding._dragOut(this.lastLanding,c.clientX,c.clientY,c),this.lastLanding=0,this._onNotFound&&this._onNotFound())
};dhtmlDragAndDropObject.prototype.stopDrag=function(e,d){dragger=window.dhtmlDragAndDrop;if(!d){dragger.stopFrameRoute();var f=dragger.lastLanding;dragger.lastLanding=null;f&&f.dragLanding._drag(dragger.dragStartNode,dragger.dragStartObject,f,_isIE?event.srcElement:e.target)
}dragger.lastLanding=null;dragger.dragNode&&dragger.dragNode.parentNode==document.body&&dragger.dragNode.parentNode.removeChild(dragger.dragNode);dragger.dragNode=0;dragger.gldragNode=0;dragger.fx=0;dragger.fy=0;
dragger.dragStartNode=0;dragger.dragStartObject=0;document.body.onmouseup=dragger.tempDOMU;document.body.onmousemove=dragger.tempDOMM;dragger.tempDOMU=null;dragger.tempDOMM=null;dragger.waitDrag=0};dhtmlDragAndDropObject.prototype.stopFrameRoute=function(f){f&&window.dhtmlDragAndDrop.stopDrag(1,1);
for(var e=0;e<window.frames.length;e++){try{window.frames[e]!=f&&window.frames[e].dhtmlDragAndDrop&&window.frames[e].dhtmlDragAndDrop.stopFrameRoute(window)}catch(h){}}try{parent.dhtmlDragAndDrop&&parent!=window&&parent!=f&&parent.dhtmlDragAndDrop.stopFrameRoute(window)
}catch(g){}};dhtmlDragAndDropObject.prototype.initFrameRoute=function(g,f){if(g){window.dhtmlDragAndDrop.preCreateDragCopy(),window.dhtmlDragAndDrop.dragStartNode=g.dhtmlDragAndDrop.dragStartNode,window.dhtmlDragAndDrop.dragStartObject=g.dhtmlDragAndDrop.dragStartObject,window.dhtmlDragAndDrop.dragNode=g.dhtmlDragAndDrop.dragNode,window.dhtmlDragAndDrop.gldragNode=g.dhtmlDragAndDrop.dragNode,window.document.body.onmouseup=window.dhtmlDragAndDrop.stopDrag,window.waitDrag=0,!_isIE&&f&&(!_isFF||_FFrv<1.8)&&window.dhtmlDragAndDrop.calculateFramePosition()
}try{parent.dhtmlDragAndDrop&&parent!=window&&parent!=g&&parent.dhtmlDragAndDrop.initFrameRoute(window)}catch(k){}for(var i=0;i<window.frames.length;i++){try{window.frames[i]!=g&&window.frames[i].dhtmlDragAndDrop&&window.frames[i].dhtmlDragAndDrop.initFrameRoute(window,!g||f?1:0)
}catch(h){}}};_OperaRv=_KHTMLrv=_FFrv=_isChrome=_isMacOS=_isKHTML=_isOpera=_isIE=_isFF=!1;navigator.userAgent.indexOf("Macintosh")!=-1&&(_isMacOS=!0);navigator.userAgent.toLowerCase().indexOf("chrome")>-1&&(_isChrome=!0);
if(navigator.userAgent.indexOf("Safari")!=-1||navigator.userAgent.indexOf("Konqueror")!=-1){_KHTMLrv=parseFloat(navigator.userAgent.substr(navigator.userAgent.indexOf("Safari")+7,5)),_KHTMLrv>525?(_isFF=!0,_FFrv=1.9):_isKHTML=!0
}else{if(navigator.userAgent.indexOf("Opera")!=-1){_isOpera=!0,_OperaRv=parseFloat(navigator.userAgent.substr(navigator.userAgent.indexOf("Opera")+6,3))}else{if(navigator.appName.indexOf("Microsoft")!=-1){if(_isIE=!0,(navigator.appVersion.indexOf("MSIE 8.0")!=-1||navigator.appVersion.indexOf("MSIE 9.0")!=-1||navigator.appVersion.indexOf("MSIE 10.0")!=-1)&&document.compatMode!="BackCompat"){_isIE=8
}}else{_isFF=!0,_FFrv=parseFloat(navigator.userAgent.split("rv:")[1])}}}dtmlXMLLoaderObject.prototype.doXPath=function(s,r,q,p){if(_isKHTML||!_isIE&&!window.XPathResult){return this.doXPathOpera(s,r)}if(_isIE){return r||(r=this.xmlDoc.nodeName?this.xmlDoc:this.xmlDoc.responseXML),r||dhtmlxError.throwError("LoadXML","Incorrect XML",[r||this.xmlDoc,this.mainObject]),q!=null&&r.setProperty("SelectionNamespaces","xmlns:xsl='"+q+"'"),p=="single"?r.selectSingleNode(s):r.selectNodes(s)||[]
}else{var o=r;r||(r=this.xmlDoc.nodeName?this.xmlDoc:this.xmlDoc.responseXML);r||dhtmlxError.throwError("LoadXML","Incorrect XML",[r||this.xmlDoc,this.mainObject]);r.nodeName.indexOf("document")!=-1?o=r:(o=r,r=r.ownerDocument);
var m=XPathResult.ANY_TYPE;if(p=="single"){m=XPathResult.FIRST_ORDERED_NODE_TYPE}var n=[],l=r.evaluate(s,o,function(){return q},m,null);if(m==XPathResult.FIRST_ORDERED_NODE_TYPE){return l.singleNodeValue
}for(var k=l.iterateNext();k;){n[n.length]=k,k=l.iterateNext()}return n}};function j(){if(!this.catches){this.catches=[]}return this}j.prototype.catchError=function(d,c){this.catches[d]=c};j.prototype.throwError=function(e,d,f){if(this.catches[e]){return this.catches[e](e,d,f)
}if(this.catches.ALL){return this.catches.ALL(e,d,f)}alert("Error type: "+e+"\nDescription: "+d);return null};window.dhtmlxError=new j;dtmlXMLLoaderObject.prototype.doXPathOpera=function(g,f){var k=g.replace(/[\/]+/gi,"/").split("/"),i=null,h=1;
if(!k.length){return[]}if(k[0]=="."){i=[f]}else{if(k[0]==""){i=(this.xmlDoc.responseXML||this.xmlDoc).getElementsByTagName(k[h].replace(/\[[^\]]*\]/g,"")),h++}else{return[]}}for(;h<k.length;h++){i=this._getAllNamedChilds(i,k[h])
}k[h-1].indexOf("[")!=-1&&(i=this._filterXPath(i,k[h-1]));return i};dtmlXMLLoaderObject.prototype._filterXPath=function(f,e){for(var h=[],e=e.replace(/[^\[]*\[\@/g,"").replace(/[\[\]\@]*/g,""),g=0;g<f.length;
g++){f[g].getAttribute(e)&&(h[h.length]=f[g])}return h};dtmlXMLLoaderObject.prototype._getAllNamedChilds=function(g,f){var k=[];_isKHTML&&(f=f.toUpperCase());for(var i=0;i<g.length;i++){for(var h=0;h<g[i].childNodes.length;
h++){_isKHTML?g[i].childNodes[h].tagName&&g[i].childNodes[h].tagName.toUpperCase()==f&&(k[k.length]=g[i].childNodes[h]):g[i].childNodes[h].tagName==f&&(k[k.length]=g[i].childNodes[h])}}return k};function dhtmlXHeir(e,d){for(var f in d){typeof d[f]=="function"&&(e[f]=d[f])
}return e}function dhtmlxEvent(e,d,f){e.addEventListener?e.addEventListener(d,f,!1):e.attachEvent&&e.attachEvent("on"+d,f)}dtmlXMLLoaderObject.prototype.xslDoc=null;dtmlXMLLoaderObject.prototype.setXSLParamValue=function(f,e,h){if(!h){h=this.xslDoc
}if(h.responseXML){h=h.responseXML}var g=this.doXPath("/xsl:stylesheet/xsl:variable[@name='"+f+"']",h,"http://www.w3.org/1999/XSL/Transform","single");if(g!=null){g.firstChild.nodeValue=e}};dtmlXMLLoaderObject.prototype.doXSLTransToObject=function(f,e){if(!f){f=this.xslDoc
}if(f.responseXML){f=f.responseXML}if(!e){e=this.xmlDoc}if(e.responseXML){e=e.responseXML}if(_isIE){g=new ActiveXObject("Msxml2.DOMDocument.3.0");try{e.transformNodeToObject(f,g)}catch(h){g=e.transformNode(f)
}}else{if(!this.XSLProcessor){this.XSLProcessor=new XSLTProcessor,this.XSLProcessor.importStylesheet(f)}var g=this.XSLProcessor.transformToDocument(e)}return g};dtmlXMLLoaderObject.prototype.doXSLTransToString=function(e,d){var f=this.doXSLTransToObject(e,d);
return typeof f=="string"?f:this.doSerialization(f)};dtmlXMLLoaderObject.prototype.doSerialization=function(d){if(!d){d=this.xmlDoc}if(d.responseXML){d=d.responseXML}if(_isIE){return d.xml}else{var c=new XMLSerializer;
return c.serializeToString(d)}};dhtmlxEventable=function(a){a.attachEvent=function(a,c,d){a="ev_"+a.toLowerCase();this[a]||(this[a]=new this.eventCatcher(d||this));return a+":"+this[a].addEvent(c)};a.callEvent=function(a,c){a="ev_"+a.toLowerCase();
return this[a]?this[a].apply(this,c):!0};a.checkEvent=function(a){return !!this["ev_"+a.toLowerCase()]};a.eventCatcher=function(a){var c=[],d=function(){for(var d=!0,g=0;g<c.length;g++){if(c[g]!=null){var f=c[g].apply(a,arguments),d=d&&f
}}return d};d.addEvent=function(a){typeof a!="function"&&(a=eval(a));return a?c.push(a)-1:!1};d.removeEvent=function(a){c[a]=null};return d};a.detachEvent=function(a){if(a!=!1){var c=a.split(":");this[c[0]].removeEvent(c[1])
}};a.detachAllEvents=function(){for(var a in this){a.indexOf("ev_")==0&&delete this[a]}};a=null};