var KeyTable=Class.create();KeyTable.prototype={initialize:function(c,b){b=b||{};this.numberOfRows=c.rows.length;this.numberOfColumns=c.columnModel.length;this.mtgId=c.mtgId;this.bodyDiv=c.bodyDiv;this.table=c.bodyTable;
this._nBody=this.table.down("tbody");this.xOldPos=null;this.yOldPos=null;this._nOldFocus=null;this.blockFlg=false;this.blockKeyCaptureFlg=false;this._nInput=null;this._bForm=b.form||false;this._bInputFocused=false;
this._sFocusClass="focus";this.xOldPos=0;this.yOldPos=0;this.event={remove:{}};this._oaoEvents={action:[],esc:[],focus:[],blur:[]};var a=this;for(var d in this._oaoEvents){if(d){a.event[d]=a.insertAddEventTemplate(d);
a.event.remove[d]=a.insertRemoveEventTemplate(d)}}Event.observe(document,"click",function(f){var g=f.target;var e=false;while(g){if(g==a.table){e=true;break}g=g.parentNode}if(!e){a.blur(true)}});this._nBody.getElementsBySelector("td").each(function(e){Event.observe(e,"click",function(f){var g=a.table.getElementsBySelector("tr."+a._sFocusClass);
if(g.length>0){g[0].removeClassName(a._sFocusClass)}a.onClick(f)})});if(Prototype.Browser.Gecko||Prototype.Browser.Opera){Event.observe(document,"keypress",function(f){var e=a.onKeyPress(f);if(!e){f.preventDefault()
}})}else{Event.observe(document,"keydown",function(f){var e=a.onKeyPress(f);if(!e){f.preventDefault()}})}},insertAddEventTemplate:function(b){var a=this;return function(c,e,d){if(typeof c=="number"&&typeof e=="number"&&typeof d=="function"){a.addEvent(b,a.getCellFromCoords(c,e),d)
}else{if(typeof c=="object"&&typeof e=="function"){a.addEvent(b,c,e)}}}},insertRemoveEventTemplate:function(b){var a=this;return function(c,e,d){if(typeof arguments[0]=="number"&&typeof arguments[1]=="number"){if(typeof arguments[2]=="function"){a.removeEvent(b,a.getCellFromCoords(c,e),d)
}else{a.removeEvent(b,a.getCellFromCoords(c,e))}}else{if(typeof arguments[0]=="object"){if(typeof arguments[1]=="function"){a.removeEvent(b,c,e)}else{a.removeEvent(b,c)}}}}},addEvent:function(c,b,a){this._oaoEvents[c].push({nCell:b,fn:a})
},removeEvent:function(f,e,c){var d=0;for(var b=0,a=this._oaoEvents[f].length;b<a-d;b++){if(typeof c!="undefined"){if(this._oaoEvents[f][b-d].nCell==e&&this._oaoEvents[f][b-d].fn==c){this._oaoEvents[f].splice(b-d,1);
d++}}else{if(this._oaoEvents[f][b].nCell==e){this._oaoEvents[f].splice(b,1);return 1}}}return d},onKeyPress:function(c){if(this.blockFlg||!this.blockKeyCaptureFlg){return true}if(c.metaKey||c.altKey||c.ctrlKey){return true
}var b,e;b=this.xOldPos;e=this.yOldPos;var d=(c.keyCode==9&&c.shiftKey)?-1:c.keyCode;var a=null;while(true){switch(d){case 13:this.eventFire("action",this._nOldFocus);return false;case 27:if(!this.eventFire("esc",this._nOldFocus)){this.blur()
}break;case -1:case 37:if(this._bInputFocused){return true}if(this.xOldPos>0){b=this.xOldPos-1;e=this.yOldPos}else{if(this.yOldPos>0){b=this.numberOfColumns-1;e=this.yOldPos-1}else{if(d==-1&&this._bForm){this._bInputFocused=true;
this._nInput.focus();setTimeout(function(){this._bInputFocused=false},0);this.blockKeyCaptureFlg=false;this.blur();return true}else{return false}}}break;case 38:if(this._bInputFocused){return true}if(this.yOldPos>0){b=this.xOldPos;
e=this.yOldPos-1}else{return false}break;case 9:case 39:if(this._bInputFocused){return true}if(this.xOldPos<this.numberOfColumns-1){b=this.xOldPos+1;e=this.yOldPos}else{if(this.yOldPos<this.numberOfRows-1){b=0;
e=this.yOldPos+1}else{if(d==9&&this._bForm){this._bInputFocused=true;this._nInput.focus();setTimeout(function(){this._bInputFocused=false},0);this.blockKeyCaptureFlg=false;this.blur();return true}else{return false
}}}break;case 40:if(this._bInputFocused){return true}if(this.yOldPos<this.numberOfRows-1){b=this.xOldPos;e=this.yOldPos+1}else{return false}break;default:return true}a=this.getCellFromCoords(b,e);if(a.getStyle("display")!="none"){break
}else{this.xOldPos=b;this.yOldPos=e}}this.setFocus(a);return false},setFocus:function(d,j){if(this._nOldFocus==d){return}if(typeof j=="undefined"){j=true}if(this._nOldFocus!==null){this.removeFocus(this._nOldFocus)
}$(d).addClassName(this._sFocusClass);$(d).up("tr").addClassName(this._sFocusClass);var e=this.getCoordsFromCell(d);this._nOldFocus=d;this.xOldPos=e[0];this.yOldPos=e[1];if(j){var g=this.bodyDiv.clientHeight;
var i=this.bodyDiv.clientWidth;var c=this.bodyDiv.scrollTop;var f=this.bodyDiv.scrollLeft;var a=d.offsetHeight;var b=d.offsetWidth;var h=this.getPosition(d);if(h[1]+a>c+g){this.setScrollTop(h[1]+a-g)}else{if(h[1]<c){this.setScrollTop(h[1])
}}if(h[0]+b>f+i){this.setScrollLeft(h[0]+b-i)}else{if(h[0]<f){this.setScrollLeft(h[0])}}}this.eventFire("focus",this._nOldFocus)},setScrollTop:function(a){this.bodyDiv.scrollTop=a},setScrollLeft:function(a){this.bodyDiv.scrollLeft=a
},eventFire:function(e,c){var d=0;var a=this._oaoEvents[e];for(var b=0;b<a.length;b++){if(a[b].nCell==c){a[b].fn(c);d++}}return d},blur:function(a){if(!this._nOldFocus){return}this.removeFocus(this._nOldFocus,a);
this.releaseKeys()},removeFocus:function(b,a){if(!b){return}b.removeClassName(this._sFocusClass);if(!a){b.up().removeClassName(this._sFocusClass)}this.eventFire("blur",b)},getPosition:function(c){var b=0;
var a=0;if(c.offsetParent){b=c.offsetLeft;a=c.offsetTop}return[b,a]},getCoordsFromCell:function(c){var b=c.id;var a=b.substring(b.indexOf("_")+1,b.length).split(",");return[parseInt(a[0]),parseInt(a[1])]
},getCellFromCoords:function(a,b){return $("mtgC"+this.mtgId+"_"+a+","+b)},onClick:function(a){var b=a.target;while(b.nodeName!="TD"){b=b.parentNode}this.setFocus(b);this.captureKeys()},captureKeys:function(){if(!this.blockKeyCaptureFlg){this.blockKeyCaptureFlg=true
}},releaseKeys:function(){this.blockKeyCaptureFlg=false}};