var MyTableGrid=Class.create();MyTableGrid.imagesBase=$Comp.path+"/grid/css/"+$Comp.skin+"/images/";MyTableGrid.prototype={version:"1.0.3",imageRefs:{colMoveTop:MyTableGrid.imagesBase+"col-move-top.gif",colMoveBottom:MyTableGrid.imagesBase+"col-move-bottom.gif",sortAscendingIcon:MyTableGrid.imagesBase+"sort_ascending.png",sortDescendingIcon:MyTableGrid.imagesBase+"sort_descending.png",prevIcon:MyTableGrid.imagesBase+"prev.gif",nextIcon:MyTableGrid.imagesBase+"next.gif",firstIcon:MyTableGrid.imagesBase+"first.gif",lastIcon:MyTableGrid.imagesBase+"last.gif",prevDisabledIcon:MyTableGrid.imagesBase+"prev-disabled.gif",nextDisabledIcon:MyTableGrid.imagesBase+"next-disabled.gif",firstDisabledIcon:MyTableGrid.imagesBase+"first-disabled.gif",lastDisabledIcon:MyTableGrid.imagesBase+"last-disabled.gif",ySepIcon:MyTableGrid.imagesBase+"y-sep.png",mtgLoaderIcon:MyTableGrid.imagesBase+"mtg-loader.gif",mtgSortArrowAscIcon:MyTableGrid.imagesBase+"sort-arrow-asc.png",mtgSortArrowDescIcon:MyTableGrid.imagesBase+"sort-arrow-desc.png",mtgMagnifierIcon:MyTableGrid.imagesBase+"magnifier.png"},messages:{totalDisplayMsg:"<strong>{total}</strong> records found",rowsDisplayMsg:", displaying <strong>{from}</strong> to <strong>{to}</strong>",pagePromptMsg:"<td><strong>Page:</strong></td><td>{input}</td><td>of <strong>{pages}</strong></td>",pagerNoDataFound:"<strong>No records found</strong>"},initialize:function(b){this.mtgId=$$(".myTableGrid").length+1;
this.tableModel=b;this.columnModel=b.columnModel||[];this.rows=b.rows||[];this.options=b.options||{};this.name=b.name||"";this.fontSize=11;this.headerHeight=24;this.cellHeight=24;this.pagerHeight=24;this.scrollBarWidth=18;
this.topPos=0;this.leftPos=0;this.selectedHCIndex=0;this.pager=this.options.pager||null;this.pager.pageParameter=this.options.pager.pageParameter||"page";this.url=b.url||null;this.request=b.request||{};
this.sortColumnParameter=this.options.sortColumnParameter||"sortColumn";this.ascDescFlagParameter=this.options.ascDescFlagParameter||"ascDescFlg";this.sortedColumnIndex=0;this.onCellFocus=this.options.onCellFocus||null;
this.onCellBlur=this.options.onCellBlur||null;this.modifiedRows=[];this.afterRender=this.options.afterRender||null;for(var a=0;a<this.columnModel.length;a++){if(!this.columnModel[a].hasOwnProperty("editable")){this.columnModel[a].editable=false
}if(!this.columnModel[a].hasOwnProperty("visible")){this.columnModel[a].visible=true}if(!this.columnModel[a].hasOwnProperty("type")){this.columnModel[a].type="string"}this.columnModel[a].positionIndex=a
}this.targetColumnId=null;this.editedCellId=null;this.gap=2;if(Prototype.Browser.WebKit){this.gap=0}},render:function(c){this.target=c;var b=document.createDocumentFragment();$(c).innerHTML=this.createTableLayout();
var d=this.mtgId;this.tableDiv=$("myTableGrid"+d);this.headerRowDiv=$("headerRowDiv"+d);this.bodyDiv=$("bodyDiv"+d);this.pagerDiv=$("pagerDiv"+d);this.resizeMarkerLeft=$("resizeMarkerLeft"+d);this.resizeMarkerRight=$("resizeMarkerRight"+d);
this.dragColumn=$("dragColumn"+d);this.colMoveTopDiv=$("mtgColMoveTop"+d);this.colMoveBottomDiv=$("mtgColMoveBottom"+d);this.scrollLeft=0;this.targetColumnId=null;var a=this;Event.observe(this.bodyDiv,"dom:dataLoaded",function(){if(a.rows.length>0){a.bodyTable=$("mtgBT"+d);
a.applyCellCallbacks();a.applyHeaderButtons();a.makeAllColumnResizable();a.makeAllColumnDraggable();a.applySettingMenuBehavior();a.keys=new KeyTable(a);a.addKeyBehavior()}if(a.pager){if(a.rows.length>0){$("mtgLoader"+d).hide()
}a.addPagerBehavior()}if(a.afterRender){a.afterRender()}});if(this.rows&&this.rows.length>0){$("mtgLoader"+d).show()}setTimeout(function(){if(a.tableModel.hasOwnProperty("rows")){if(a.rows.length>0){a.bodyDiv.innerHTML=a.createTableBody(a.rows);
a.pagerDiv.innerHTML=a.updatePagerInfo();a.bodyDiv.fire("dom:dataLoaded")}}else{a.retrieveDataFromUrl(1,true)}},0);Event.observe($("bodyDiv"+d),"scroll",function(){a.syncScroll()});if(this.options.onSave){Event.observe($("mtgSaveBtn"+d),"click",function(){a.options.onSave()
})}Event.observe(window,"resize",function(){a.resize()})},createTableLayout:function(e){var g=$(this.target);var b=this.options.width||(g.getWidth()-this.fullPadding(g,"left")-this.fullPadding(g,"right"))+"px";
var n=this.options.height||(g.getHeight()-this.fullPadding(g,"top")-this.fullPadding(g,"bottom"))+"px";var a=this.mtgId;var m=this.columnModel;var k=this.gap;var f=this.imageRefs;var j=this.cellHeight;
this.tableWidth=parseInt(b)-2;this.tableHeight=parseInt(n)-2;var h=0;for(var c=0;c<m.length;c++){h+=parseInt(m[c].width)+k}this.headerWidth=h;var l=0;var d=[];d[l++]='<div id="myTableGrid'+a+'" class="myTableGrid" style="position:relative;width:'+this.tableWidth+'"px;height:'+this.tableHeight+'px;z-index:0">';
if(this.options.title||this.options.onSave){d[l++]='<div id="mtgHeaderTitle'+a+'" class="mtgHeaderRow mtgHeaderTitle" style="position:absolute;top:'+this.topPos+"px;left:"+this.leftPos+"px;width:"+(this.tableWidth-6)+"px;height:"+(this.headerHeight-6)+'px;padding:3px;z-index:10">';
if(this.options.onSave){d[l++]='<input id="mtgSaveBtn'+a+'" class="buttonpurple" type="button" name="btnSave" value="Save">'}else{d[l++]=this.options.title}d[l++]="</div>";this.topPos+=this.headerHeight+1
}d[l++]='<div id="headerRowDiv'+a+'" class="mtgHeaderRow" style="position:absolute;top:'+this.topPos+"px;left:"+this.leftPos+"px;width:"+this.tableWidth+"px;height:"+this.headerHeight+'px;padding:0;overflow:hidden;z-index:0">';
d[l++]='<div id="mtgHRB'+a+'" style="position:relative;padding:0;margin:0;width:'+this.headerWidth+'px">';d[l++]=this.createHeaderRow();d[l++]="</div>";d[l++]="</div>";this.topPos+=this.headerHeight+1;
this.bodyHeight=this.tableHeight-this.headerHeight-3;if(this.options.title){this.bodyHeight=this.bodyHeight-this.headerHeight-1}if(this.options.pager){this.bodyHeight=this.bodyHeight-this.pagerHeight}d[l++]='<div id="bodyDiv'+a+'" class="mtgBody" style="position:absolute;top:'+this.topPos+"px;left:"+this.leftPos+"px;width:"+this.tableWidth+"px;height:"+this.bodyHeight+'px;overflow:auto;z-index:10">';
d[l++]="</div>";if(this.options.pager){this.topPos+=this.bodyHeight+2;d[l++]='<div id="pagerDiv'+a+'" class="mtgPager" style="position:absolute;top:'+this.topPos+"px;left:0;bottom:0;width:"+(this.tableWidth-2)+"px;height:"+(this.pagerHeight-4)+'px">';
d[l++]=this.updatePagerInfo(true);d[l++]="</div>"}d[l++]='<div id="mtgSB'+a+'" class="mtgSettingButton">';d[l++]="</div>";d[l++]=this.createSettingMenu();d[l++]='<div id="mtgHB'+a+'" class="mtgHeaderButton" style="width:14px;height:'+this.headerHeight+'px">';
d[l++]="</div>";d[l++]='<div id="mtgHBM'+a+'" class="mtgMenu">';d[l++]="<ul>";d[l++]="<li>";d[l++]='<a id="mtgSortAsc'+a+'" class="mtgMenuItem" href="javascript:void(0)">';d[l++]='<table cellspacing="0" cellpadding="0" width="100%" border="0">';
d[l++]='<tr><td width="25">&nbsp;<img src="'+f.sortAscendingIcon+'" width="16" height="16" border="0" class="mtgMenuItemIcon mtgSortAscendingIcon"></td>';d[l++]="<td>Sort Ascending</td></tr></table>";d[l++]="</a>";
d[l++]="</li>";d[l++]="<li>";d[l++]='<a id="mtgSortDesc'+a+'" class="mtgMenuItem" href="javascript:void(0)">';d[l++]='<table cellspacing="0" cellpadding="0" width="100%" border="0">';d[l++]='<tr><td width="25">&nbsp;<span><img src="'+f.sortDescendingIcon+'" width="16" height="16" border="0" class="mtgMenuItemIcon mtgSortDescendingIcon"></span></td>';
d[l++]="<td>Sort Descending</td></tr></table>";d[l++]="</a>";d[l++]="</li>";d[l++]='<li class="mtgSelectAll">';d[l++]='<a class="mtgMenuItem" href="javascript:void(0)">';d[l++]='<table cellspacing="0" cellpadding="0" width="100%" border="0">';
d[l++]='<tr><td width="25"><span class="mtgMenuItemChk"><input type="checkbox" id="mtgSelectAll'+a+'"></span></td>';d[l++]="<td>Select All</td></tr></table>";d[l++]="</a>";d[l++]="</li>";d[l++]="</ul>";
d[l++]="</div>";d[l++]='<div id="resizeMarkerLeft'+a+'" class="mtgResizeMarker">';d[l++]="</div>";d[l++]='<div id="resizeMarkerRight'+a+'" class="mtgResizeMarker">';d[l++]="</div>";d[l++]="</div>";d[l++]='<div id="mtgColMoveTop'+a+'" style="position:absolute;width:9px;height:9px;top:0;left:0;z-index:50;visibility:hidden">';
d[l++]='<img src="'+f.colMoveTop+'" width="9" height="9">';d[l++]="</div>";d[l++]='<div id="mtgColMoveBottom'+a+'" style="position:absolute;width:9px;height:9px;top:0;left:0;z-index:50;visibility:hidden">';
d[l++]='<img src="'+f.colMoveBottom+'" width="9" height="9">';d[l++]="</div>";d[l++]='<div id="dragColumn'+a+'" class="dragColumn" style="width:100px;height:18px;">';d[l++]='<span class="columnTitle">&nbsp;</span>';
d[l++]='<div class="drop-no">&nbsp;</div>';d[l++]="</div>";return d.join("")},createHeaderRow:function(){var h='<th id="mtgHC{id}_{x}" width="{width}" style="width:{width}px;padding:0;margin:0" class="mtgHeaderCell mtgHC{id}">';
var o='<th id="mtgHC{id}_{x}" width="{width}" style="width:{width}px;padding:0;margin:0;border-right:none" class="mtgHeaderCell mtgHC{id}">';var d='<div id="mtgIHC{id}_{x}" class="mtgInnerHeaderCell mtgIHC{id}" style="position:relative;width:{width}px;height:{height}px;padding:3px;z-index:20">';
var f='<div id="mtgIHC{id}_{x}" class="mtgInnerHeaderCell" style="position:relative;width:{width}px;height:{height}px;padding:3px;z-index:20">';var a='<div id="mtgHS{id}_{x}" class="mtgHS mtgHS{id}" style="position:absolute;top:0;right:-4px;width:1px;height:{height}px">';
var c='<img id="mtgSortIcon{id}_{x}" width="8" height="4" style="display:none">';var m=this.columnModel;var b=this.mtgId;var k=(this.gap==0)?2:0;var j=this.headerHeight-6;var l=0;var g=[];g[l++]='<table id="mtgHRT'+b+'" width="'+this.headerWidth+'" cellpadding="0" cellspacing="0" border="0" class="mtgHeaderRowTable">';
g[l++]="<thead>";g[l++]="<tr>";for(var e=0;e<m.length;e++){var n=m[e];var p=h.replace(/\{id\}/g,b);p=p.replace(/\{x\}/g,e);p=p.replace(/\{width\}/g,parseInt(n.width));g[l++]=p;p=d.replace(/\{id\}/g,b);
p=p.replace(/\{x\}/g,e);p=p.replace(/\{width\}/g,(parseInt(n.width)-8-k));p=p.replace(/\{height\}/g,j);g[l++]=p;g[l++]=n.title;p=c.replace(/\{id\}/g,b);p=p.replace(/\{x\}/g,e);g[l++]=p;p=a.replace(/\{id\}/g,b);
p=p.replace(/\{x\}/g,e);p=p.replace(/\{height\}/g,this.headerHeight);g[l++]=p;g[l++]="</div>";g[l++]="</div>";g[l++]="</th>"}var p=o.replace(/\{id\}/g,b);p=p.replace(/\{x\}/g,e);p=p.replace(/\{width\}/g,"20");
g[l++]=p;p=f.replace(/\{id\}/g,b);p=p.replace(/\{x\}/g,e);p=p.replace(/\{width\}/g,"20");p=p.replace(/\{height\}/g,j);g[l++]=p;g[l++]="&nbsp";g[l++]="</div>";g[l++]="</th>";g[l++]="</tr>";g[l++]="</thead>";
g[l++]="</table>";return g.join("")},createTableBody:function(m){var s=this.mtgId;var q='<td id="mtgC{id}_{x},{y}" height="{height}" width="{width}" style="width:{width}px;height:{height}px;padding:0;margin:0" class="mtgCell mtgC{id} mtgC{id}_{x} mtgR{id}_{y}">';
var p='<div id="mtgIC{id}_{x},{y}" style="width:{width}px;height:{height}px;padding:3px;text-align:{align}" class="mtgInnerCell mtgIC{id} mtgIC{id}_{x} mtgIR{id}_{y}">';var z='<input id="mtgInput{id}_{x},{y}" name="mtgInput{id}_{x},{y}" type="checkbox" value="{value}" class="mtgInput{id}_{x} mtgInputCheckbox">';
var g='<input id="mtgInput{id}_{x},{y}" name="mtgInput{id}_{x}" type="radio" value="{value}" class="mtgInput{id}_{x} mtgInputRadio">';if(Prototype.Browser.Opera||Prototype.Browser.WebKit){z='<input id="mtgInput{id}_{x},{y}" name="mtgInput{id}_{x},{y}" type="checkbox" value="{value}" class="mtgInput{id}_{x}">';
g='<input id="mtgInput{id}_{x},{y}" name="mtgInput{id}_{x}" type="radio" value="{value}" class="mtgInput{id}_{x}">'}var a=this.cellHeight;var c=a-6;var k=this.headerWidth;var w=this.columnModel;var b=this.fontSize;
var r=((this.gap==0)?2:0);var n=[];var o=0;n[o++]='<table id="mtgBT'+s+'" border="0" cellspacing="0" cellpadding="0" width="'+k+'" class="mtgBodyTable">';n[o++]="<tbody>";for(var v=0;v<m.length;v++){var h=m[v];
n[o++]='<tr id="mtgRow'+s+"_"+v+'" class="mtgRow'+s+'">';for(var u=0;u<h.length;u++){var A=w[u].positionIndex;var d=w[u].type||"string";var t=parseInt(w[u].width);var f=t-6-r;var e=w[u].editor||null;var x=!(e=="checkbox"||e instanceof MyTableGrid.CellCheckbox||e=="radio"||e instanceof MyTableGrid.CellRadioButton);
var l="left";if(!w[u].hasOwnProperty("renderer")){l=(d=="string")?"left":"right"}if(w[u].hasOwnProperty("align")){l=w[u].align}var y=q.replace(/\{id\}/g,s);y=y.replace(/\{x\}/g,u);y=y.replace(/\{y\}/g,v);
y=y.replace(/\{width\}/g,t);y=y.replace(/\{height\}/g,a);n[o++]=y;y=p.replace(/\{id\}/g,s);y=y.replace(/\{x\}/g,u);y=y.replace(/\{y\}/g,v);y=y.replace(/\{width\}/,f);y=y.replace(/\{height\}/,c);y=y.replace(/\{align\}/,l);
n[o++]=y;if(x){if(!w[u].hasOwnProperty("renderer")){n[o++]=this.getStringMask(h[A],t,b)}else{n[o++]=w[u].renderer(h[A])}}else{if(e=="checkbox"||e instanceof MyTableGrid.CellCheckbox){y=z.replace(/\{id\}/g,s);
y=y.replace(/\{x\}/g,u);y=y.replace(/\{y\}/g,v);y=y.replace(/\{value\}/,h[A]);n[o++]=y}else{if(e=="radio"||e instanceof MyTableGrid.CellRadioButton){y=g.replace(/\{id\}/g,s);y=y.replace(/\{x\}/g,u);y=y.replace(/\{y\}/g,v);
y=y.replace(/\{value\}/,h[A]);n[o++]=y}}}n[o++]="</div>";n[o++]="</td>"}n[o++]="</tr>"}n[o++]="</tbody>";n[o++]="</table>";return n.join("")},applyCellCallbacks:function(){for(var a=0;a<this.columnModel.length;
a++){var b=this.columnModel[a].editor;if((b instanceof MyTableGrid.CellRadioButton&&b.onClickCallback)||(b instanceof MyTableGrid.CellCheckbox&&b.onClickCallback)){$$(".mtgInput"+this.mtgId+"_"+a).each(function(c){c.onclick=(function(d){return function(){d.onClickCallback(c.value,true)
}})(b)})}}},getStringMask:function(d,b,c){var a=d;if(Math.round(d.length*c*0.6)>b){var e=Math.round((b/c)*1.5);a=d.substring(0,e-3)+" ..."}return a},createSettingMenu:function(){var a=this.mtgId;var g=this.columnModel;
var c=this.bodyHeight+30;var f=(Prototype.Browser.IE)?25:22;var j=(g.length*25>c)?c:g.length*f;var e=[];var h=0;e[h++]='<div id="mtgSM'+a+'" class="mtgMenu" style="height:'+j+'px">';e[h++]="<ul>";for(var d=0;
d<g.length;d++){var b=g[d];e[h++]="<li>";e[h++]='<a href="#" class="mtgMenuItem">';e[h++]='<table border="0" cellpadding="0" cellspacing="0" width="100%">';e[h++]='<tr><td width="25"><span><input type="checkbox" checked="'+b.visible+'"></span></td>';
e[h++]="<td>&nbsp;"+b.title+"</td></tr>";e[h++]="</table>";e[h++]="</a>";e[h++]="</li>"}e[h++]="</ul>";e[h++]="</div>";return e.join("")},applySettingMenuBehavior:function(){var d=$("mtgSM"+this.mtgId);
var c=d.getWidth();var b=$("mtgSB"+this.mtgId);Event.observe(b,"click",function(){if(d.getStyle("visibility")=="hidden"){var e=b.offsetTop;var f=b.offsetLeft;d.setStyle({top:(e+16)+"px",left:(f-c+16)+"px",visibility:"visible"})
}else{d.setStyle({visibility:"hidden"})}});Event.observe($("mtgHeaderTitle"+this.mtgId),"mousemove",function(){d.setStyle({visibility:"hidden"})});var a=this;$$("#mtgSM"+this.mtgId+" input[@type:checkbox]").each(function(f,e){f.onclick=function(){a.toggleColumnVisibility(e,f.checked)
}})},syncScroll:function(){this.scrollLeft=$("headerRowDiv"+this.mtgId).scrollLeft=$("bodyDiv"+this.mtgId).scrollLeft;$("mtgHB"+this.mtgId).setStyle({visibility:"hidden"});$("mtgHBM"+this.mtgId).setStyle({visibility:"hidden"})
},makeAllColumnResizable:function(){var e=this.mtgId;var b=0;if(this.options.title){b+=this.headerHeight}var d=$("mtgHB"+this.mtgId);var c;var a=this;$$(".mtgHS"+this.mtgId).each(function(g,f){Event.observe(g,"mousemove",function(){d.setStyle({visibility:"visible"});
c=-1;for(var j=0;j<a.columnModel.length;j++){if(f==a.columnModel[j].positionIndex){c=j;break}}if(c>=0){var k=a.bodyHeight+a.headerHeight+2;if(a.hasHScrollBar()){k=k-a.scrollBarWidth}var h=$("mtgHC"+e+"_"+c).offsetLeft-a.scrollLeft;
a.resizeMarkerLeft.setStyle({height:k+"px",top:(b+2)+"px",left:h+"px"});h+=$("mtgHC"+e+"_"+c).offsetWidth;a.resizeMarkerRight.setStyle({height:k+"px",top:(b+2)+"px",left:(h+1)+"px"})}})});new Draggable(a.resizeMarkerRight,{constraint:"horizontal",onStart:function(){a.resizeMarkerRight.setStyle({backgroundColor:"dimgray"});
a.resizeMarkerLeft.setStyle({backgroundColor:"dimgray"})},onEnd:function(){var f=parseInt(a.resizeMarkerRight.getStyle("left"))-parseInt(a.resizeMarkerLeft.getStyle("left"));if(f>0&&c!=null){setTimeout(function(){a.resizeColumn(c,f)
},0)}a.resizeMarkerLeft.setStyle({backgroundColor:"transparent",left:0});a.resizeMarkerRight.setStyle({backgroundColor:"transparent"})},endeffect:false})},resizeColumn:function(d,f){var a=parseInt($("mtgHC"+this.mtgId+"_"+d).width);
var e=this.columnModel[d].editor;var c=(e=="checkbox"||e instanceof MyTableGrid.CellCheckbox||e=="radio"||e instanceof MyTableGrid.CellRadioButton);$("mtgHC"+this.mtgId+"_"+d).width=f;$("mtgHC"+this.mtgId+"_"+d).setStyle({width:f+"px"});
$("mtgIHC"+this.mtgId+"_"+d).setStyle({width:(f-8-((this.gap==0)?2:0))+"px"});var b=this;$$(".mtgC"+this.mtgId+"_"+d).each(function(g){g.width=f;g.setStyle({width:f+"px"})});$$(".mtgIC"+this.mtgId+"_"+d).each(function(g,i){var h=b.getValueAt(d,i);
g.setStyle({width:(f-6-((b.gap==0)?2:0))+"px"});if(!c){if(b.columnModel[d].renderer){h=b.columnModel[d].renderer(h)}if(!h.match(/^<img/)){g.innerHTML=b.getStringMask(h,f,b.fontSize)}else{g.innerHTML=h}}});
this.headerWidth=this.headerWidth-(a-f);$("mtgHRT"+this.mtgId).width=this.headerWidth;$("mtgBT"+this.mtgId).width=this.headerWidth;this.columnModel[d].width=f;this.syncScroll()},hasHScrollBar:function(){return(this.headerWidth+20)>this.tableWidth
},makeAllColumnDraggable:function(){this.separators=[];var c=0;var e=this.mtgId;var b=this;$$(".mtgHS"+this.mtgId).each(function(f){b.separators[c++]=f});var a=0;if(this.options.title){a+=this.headerHeight
}var d=$("dragColumn"+e);$$(".mtgIHC"+e).each(function(h,f){var g=-1;Event.observe(h,"mousemove",function(){var j=h.up().offsetLeft;d.setStyle({top:(a+15)+"px",left:(j-b.scrollLeft+15)+"px"})});var i=new Draggable(d,{handle:h,onStart:function(){for(var j=0;
j<b.columnModel.length;j++){if(f==b.columnModel[j].positionIndex){g=j;break}}if(Prototype.Browser.IE){Event.observe(document.body,"drag",function(){return false},false);Event.observe(document.body,"selectstart",function(){return false
},false)}d.down("span").innerHTML=b.columnModel[g].title;d.setStyle({visibility:"visible"})},onDrag:function(){var j=parseInt(d.getStyle("left"));var k=parseInt(d.getStyle("width"));setTimeout(function(){b.detectDroppablePosition(j+k/2,k,d,g)
},0)},onEnd:function(){d.setStyle({visibility:"hidden"});b.colMoveTopDiv.setStyle({visibility:"hidden"});b.colMoveBottomDiv.setStyle({visibility:"hidden"});if(g>=0&&b.targetColumnId>=0){setTimeout(function(){b.moveColumn(g,b.targetColumnId);
g=-1},0)}},endeffect:false})})},detectDroppablePosition:function(a,b,d,h){var f=-8;if(this.options.title){f+=this.headerHeight}var l=0;var m=this.columnModel;var k=this.gap;var c=this.scrollLeft;var n=this.colMoveTopDiv;
var g=this.colMoveBottomDiv;for(var e=0;e<m.length;e++){if(m[e].visible){l+=parseInt(m[e].width)+k}if(a>(l-c)&&(a-(l-this.scrollLeft))<(b/2)){n.setStyle({top:f+"px",left:(l-c-4)+"px",visibility:"visible"});
g.setStyle({top:(f+34)+"px",left:(l-c-4)+"px",visibility:"visible"});this.targetColumnId=e;var j=(e!=h)?"drop-yes":"drop-no";d.down("div").className=j;break}else{n.setStyle({visibility:"hidden"});g.setStyle({visibility:"hidden"});
this.targetColumnId=null;d.down("div").className="drop-no"}}},moveColumn:function(v,f){if(v==null||f==null||v==f||(f+1==v&&v==this.columnModel.length-1)){return}var t=this.mtgId;var e=this.columnModel;
var r=(this.gap==0)?2:0;var m=this.keys;var j=this.rows;var q=this;$("mtgHB"+t).setStyle({visibility:"hidden"});this.blurCellElement(m._nOldFocus);m.blur();if(f==0){var z=$("mtgHC"+t+"_"+v).remove();var d=$("mtgHC"+t+"_"+f);
d.up().insertBefore(z,d);var o=[];var n=0;$$(".mtgC"+t+"_"+v).each(function(c){o[n++]=c.remove()});for(var w=0;w<j.length;w++){var s=$("mtgC"+t+"_"+f+","+w);s.up().insertBefore(o[w],s)}}else{if(f>v&&f<e.length-1){var z=$("mtgHC"+t+"_"+v).remove();
var b=f+1;var d=$("mtgHC"+t+"_"+b);d.up().insertBefore(z,d);var o=[];var n=0;$$(".mtgC"+t+"_"+v).each(function(c){o[n++]=c.remove()});for(var w=0;w<j.length;w++){var s=$("mtgC"+t+"_"+b+","+w);s.up().insertBefore(o[w],s)
}}else{if(f<v){var z=$("mtgHC"+t+"_"+v).remove();var b=f+1;var d=$("mtgHC"+t+"_"+b);d.up().insertBefore(z,d);var o=[];var n=0;$$(".mtgC"+t+"_"+v).each(function(c){o[n++]=c.remove()});for(var w=0;w<j.length;
w++){var s=$("mtgC"+t+"_"+b+","+w);s.up().insertBefore(o[w],s)}}else{if(f==e.length-1){var a=$("mtgHC"+t+"_"+v).up();var z=$("mtgHC"+t+"_"+v).remove();var h=$("mtgHC"+t+"_"+e.length);a.insertBefore(z,h);
var o=[];var n=0;$$(".mtgC"+t+"_"+v).each(function(c){o[n++]=c.remove()});for(var w=0;w<j.length;w++){var a=$("mtgRow"+t+"_"+w);a.insert(o[w])}}}}}var y=e.length;var g=e[v];e[v]=null;e=e.compact();var A=[];
var u=0;var l=f;if(f>0&&f<v){l++}for(var x=0;x<y;x++){if(x==l){A[u++]=g}if(x<(y-1)){A[u++]=e[x]}}e=this.columnModel=A;var p=$("mtgHRT"+t).down("tr");p.getElementsBySelector("th").each(function(i,c){if(c<e.length){i.id="mtgHC"+t+"_"+c;
var k=i.down("div");k.id="mtgIHC"+t+"_"+c;k.down("img").id="mtgSortIcon"+t+"_"+c;k.down("div").id="mtgHS"+t+"_"+c}});for(var w=0;w<j.length;w++){$$(".mtgR"+t+"_"+w).each(function(i,c){i.id="mtgC"+t+"_"+c+","+w;
i.className="mtgCell mtgC"+t+" mtgC"+t+"_"+c+" mtgR"+t+"_"+w});$$(".mtgIR"+t+"_"+w).each(function(k,i){k.id="mtgIC"+t+"_"+i+","+w;k.className="mtgInnerCell mtgIC"+t+" mtgIC"+t+"_"+i+" mtgIR"+t+"_"+w;if(k.firstChild.tagName=="INPUT"){var c=k.firstChild;
c.id="mtgInput"+t+"_"+i+","+w;c.name="mtgInput"+t+"_"+i+","+w;c.className=c.className.replace(/mtgInput.*?_.*?\s/,"mtgInput"+t+"_"+i+" ")}})}this.addKeyBehavior()},addKeyBehavior:function(){var a=this;
for(var b=0;b<this.columnModel.length;b++){if(this.columnModel[b].editable){$$(".mtgC"+a.mtgId+"_"+b).each(function(c){a.keys.event.remove.action(c);a.keys.event.remove.esc(c);a.keys.event.action(c,function(){if(a.editedCellId==null||a.editedCellId!=c.id){a.editedCellId=c.id;
a.editCellElement(c)}else{a.blurCellElement(c);a.editedCellId=null}});a.keys.event.esc(c,function(){a.blurCellElement(c);a.editedCellId=null})})}if(a.onCellBlur){$$(".mtgC"+a.mtgId+"_"+b).each(function(d,c){a.keys.event.remove.blur(d);
var e=(function(f,g){return function(){a.onCellBlur(d,a.rows[g][f],f,g,a.columnModel[f].id)}})(b,c);a.keys.event.blur(d,e)})}$$(".mtgC"+a.mtgId+"_"+b).each(function(d,c){a.keys.event.remove.focus(d);var e=(function(f,g){return function(){if(a.keys._bInputFocused){a.blurCellElement($(a.editedCellId))
}if(a.onCellFocus){a.onCellFocus(d,a.rows[g][f],f,g,a.columnModel[f].id)}}})(b,c);a.keys.event.focus(d,e)})}},editCellElement:function(d){this.keys._bInputFocused=true;var c=parseInt(d.getStyle("width"));
var o=parseInt(d.getStyle("height"));var l=this.getCurrentPosition();var m=l[0];var j=l[1];var b="mtgIC"+this.mtgId+"_"+m+","+j;var f=$(b);var n=this.getValueAt(m,j);var g=this.columnModel[m].editor||"input";
var i=this.columnModel[m].type||"string";var a=(Prototype.Browser.IE)?"1px":"2px";var k=null;var e=(g=="input"||g instanceof MyTableGrid.CellAutocompleter||g instanceof MyTableGrid.BrowseInput);if(e){d.setStyle({height:this.cellHeight+"px"});
f.setStyle({width:c+"px",height:o+"px",padding:"0",border:"0",verticalAlign:"middle",textAlign:"left"});var h=(i=="number")?"right":"left";if(g=="input"){f.innerHTML="";k=new Element("input",{id:"mtgInput"+this.mtgId+"_"+m+","+j,type:"text",value:n});
k.addClassName("mtgInputText");k.setStyle({width:(c-9)+"px",height:(o-10)+"px",marginTop:a,marginLeft:"1px",paddingLeft:"3px",paddingRight:"3px",textAlign:h});f.appendChild(k);k.focus();k.select()}else{if(g instanceof MyTableGrid.CellAutocompleter){n=f.innerHTML;
f.innerHTML="";k=g.render(this,{width:c,height:o,value:n,align:h});f.appendChild(k);k.focus();k.select()}else{if(g instanceof MyTableGrid.BrowseInput){n=f.innerHTML;f.innerHTML="";k=g.render(this,{width:c,height:o,value:n,align:h});
f.appendChild(k);k.down("input").focus();k.down("input").select()}}}}else{if(g=="checkbox"||g instanceof MyTableGrid.CellCheckbox){k=$("mtgInput"+this.mtgId+"_"+m+","+j);k.checked=(!k.checked);if(g instanceof MyTableGrid.CellCheckbox&&g.onClickCallback){g.onClickCallback(n,k.checked)
}this.keys._bInputFocused=false;this.editedCellId=null}else{if(g=="radio"||g instanceof MyTableGrid.CellRadioButton){k=$("mtgInput"+this.mtgId+"_"+m+","+j);k.checked=(!k.checked);if(g instanceof MyTableGrid.CellRadioButton&&g.onClickCallback){g.onClickCallback(n,k.checked)
}this.keys._bInputFocused=false;this.editedCellId=null}}}},blurCellElement:function(d){if(!this.keys._bInputFocused){return}var b=parseInt(d.getStyle("width"));var n=parseInt(d.getStyle("height"));var k=this.keys.getCoordsFromCell(d);
var l=k[0];var j=k[1];var c=this.columnModel[l].width;var a="mtgIC"+this.mtgId+"_"+l+","+j;var m=$F("mtgInput"+this.mtgId+"_"+l+","+j);var f=$(a);var g=this.columnModel[l].editor||"input";var i=this.columnModel[l].type||"string";
var h=(i=="number")?"right":"left";var e=(g=="input"||g instanceof MyTableGrid.CellAutocompleter||g instanceof MyTableGrid.BrowseInput);if(e){d.setStyle({height:this.cellHeight+"px"});f.setStyle({width:(b-6)+"px",height:(n-6)+"px",padding:"3px",textAlign:h}).update(this.getStringMask(m,c,this.fontSize))
}if(g=="input"){this.setValueAt(m,l,j)}if(g instanceof MyTableGrid.BrowseInput&&g.afterUpdateCallback){g.afterUpdateCallback(d,m)}if(this.modifiedRows.indexOf(j)==-1){this.modifiedRows.push(j)}this.keys._bInputFocused=false
},applyHeaderButtons:function(){var c=this;var h=this.mtgId;var g=$("mtgHB"+this.mtgId);var f=$("mtgHBM"+this.mtgId);var e=$("mtgSortAsc"+this.mtgId);var d=$("mtgSortDesc"+this.mtgId);var b=0;if(this.options.title){b+=this.headerHeight
}var a=-1;$$(".mtgIHC"+h).each(function(j,i){Event.observe(j,"mousemove",function(){for(var l=0;l<c.columnModel.length;l++){if(i==c.columnModel[l].positionIndex){a=l;break}}if(a==-1){return}f.setStyle({visibility:"hidden"});
var m=j.up();var k=m.offsetLeft+m.offsetWidth;k=k-16-c.scrollLeft;if(k<c.bodyDiv.clientWidth){g.setStyle({top:(b+2)+"px",left:k+"px",visibility:"visible"})}e.onclick=function(){$("mtgSortIcon"+h+"_"+a).src=c.imageRefs.mtgSortArrowAscIcon;
c.request[c.sortColumnParameter]=c.columnModel[a].id;c.request[c.ascDescFlagParameter]="ASC";c.retrieveDataFromUrl(1);$("mtgSortIcon"+h+"_"+c.sortedColumnIndex).hide();$("mtgSortIcon"+h+"_"+a).show();c.sortedColumnIndex=a
};d.onclick=function(){$("mtgSortIcon"+h+"_"+a).src=c.imageRefs.mtgSortArrowDescIcon;c.request[c.sortColumnParameter]=c.columnModel[a].id;c.request[c.ascDescFlagParameter]="DESC";c.retrieveDataFromUrl(1);
$("mtgSortIcon"+h+"_"+c.sortedColumnIndex).hide();$("mtgSortIcon"+h+"_"+a).show();c.sortedColumnIndex=a}})});Event.observe(g,"click",function(){if(f.getStyle("visibility")=="hidden"){var l=$$("#mtgHBM"+h+" .mtgSelectAll")[0];
if(c.columnModel[a].editor=="checkbox"||c.columnModel[a].editor instanceof MyTableGrid.CellCheckbox){l.show();var j=c.columnModel[a].positionIndex;l.onclick=function(){var m=$("mtgSelectAll"+h).checked;
$$(".mtgInput"+h+"_"+a).each(function(n){n.checked=m});if(c.columnModel[a].editor instanceof MyTableGrid.CellCheckbox&&c.columnModel[a].editor.onClickCallback){c.columnModel[a].editor.onClickCallback()
}}}else{l.hide()}var k=parseInt(g.getStyle("left"));var i=c.headerHeight+2;if(c.options.title){i+=c.headerHeight}f.setStyle({top:i+"px",left:k+"px",visibility:"visible"})}else{f.setStyle({visibility:"hidden"})
}})},toggleColumnVisibility:function(b,g){this.blurCellElement(this.keys._nOldFocus);this.keys.blur();var f=$("mtgHRT"+this.mtgId);var a=$("mtgBT"+this.mtgId);for(var c=0;c<this.columnModel.length;c++){if(this.columnModel[c].positionIndex==b){b=c;
break}}var e=$("mtgHC"+this.mtgId+"_"+b);$("mtgHB"+this.mtgId).setStyle({visibility:"hidden"});var d=0;if(!g){d=parseInt(e.offsetWidth);e.hide();$$(".mtgC"+this.mtgId+"_"+b).each(function(h){h.hide()});
this.columnModel[b].visible=false;this.headerWidth=this.headerWidth-d}else{e.show();d=parseInt(e.offsetWidth);$$(".mtgC"+this.mtgId+"_"+b).each(function(h){h.show()});this.columnModel[b].visible=true;this.headerWidth=this.headerWidth+d
}f.width=this.headerWidth;f.setStyle({width:this.headerWidth+"px"});a.width=this.headerWidth;a.setStyle({width:this.headerWidth+"px"})},fullPadding:function(b,c){var d=parseInt(b.getStyle("padding-"+c));
d=(isNaN(d))?0:d;var a=parseInt(b.getStyle("border-"+c+"-width"));a=(isNaN(a))?0:a;return d+a},retrieveDataFromUrl:function(a,c){var d=this.pager.pageParameter||"page";this.request[d]=a;$("mtgLoader"+this.mtgId).show();
var b=this;new Ajax.Request(this.url,{parameters:b.request,onSuccess:function(f){var e=f.responseText.evalJSON();b.rows=e.rows||[];b.pager=e.options.pager||null;if(e.rows.length>0){b.bodyDiv.innerHTML=b.createTableBody(e.rows);
b.bodyTable=$("mtgBT"+b.mtgId);if(!c){b.applyCellCallbacks();b.keys=new KeyTable(b);b.addKeyBehavior()}}b.pagerDiv.innerHTML=b.updatePagerInfo();b.addPagerBehavior();if(b.afterRender){b.afterRender()}$("mtgLoader"+b.mtgId).hide();
if(c){b.bodyDiv.fire("dom:dataLoaded")}}})},updatePagerInfo:function(g){var h=this.mtgId;var f=this.imageRefs;if(g){return'<span id="mtgLoader'+h+'" style="display:none"><img src="'+f.mtgLoaderIcon+'" width="16" height="16"></span>'
}var e=[];var a=0;var b=this.pager;if(this.pager.total>0){var d=this.messages.totalDisplayMsg;d=d.replace(/\{total\}/g,b.total);if(b.from&&b.to){d+=this.messages.rowsDisplayMsg;d=d.replace(/\{from\}/g,b.from);
d=d.replace(/\{to\}/g,b.to)}e[a++]='<span class="mtgPagerMsg">'+d+"</span>";if(b.pages){d=this.messages.pagePromptMsg;d=d.replace(/\{pages\}/g,b.pages);var c='<input type="text" name="mtgPageInput'+h+'" id="mtgPageInput'+h+'" value="'+b.currentPage+'" class="mtgPageInput" size="3" maxlength="3">';
d=d.replace(/\{input\}/g,c);e[a++]='<table class="mtgPagerTable" border="0" cellpadding="0" cellspacing="0">';e[a++]="<tbody>";e[a++]="<tr>";e[a++]='<td><span id="mtgLoader'+h+'" style="display:none"><img src="'+f.mtgLoaderIcon+'" width="16" height="16"></span></td>';
e[a++]='<td><img src="'+f.ySepIcon+'" width="2" height="13"></td>';e[a++]='<td><a id="mtgFirst'+h+'" class="mtgPagerCtrl"><img src="'+f.firstIcon+'" width="16" height="16" border="0"></a></td>';e[a++]='<td><a id="mtgPrev'+h+'" class="mtgPagerCtrl"><img src="'+f.prevIcon+'" width="16" height="16" border="0"></a></td>';
e[a++]='<td><img src="'+f.ySepIcon+'" width="2" height="13"></td>';e[a++]=d;e[a++]='<td><img src="'+f.ySepIcon+'" width="2" height="13"></td>';e[a++]='<td><a id="mtgNext'+h+'" class="mtgPagerCtrl"><img src="'+f.nextIcon+'" width="16" height="16" border="0"></a></td>';
e[a++]='<td><a id="mtgLast'+h+'" class="mtgPagerCtrl"><img src="'+f.lastIcon+'" width="16" height="16" border="0"></a></td>';e[a++]="</tr>";e[a++]="</table>"}}else{e[a++]='<span class="mtgPagerMsg">'+this.messages.pagerNoDataFound+"</span>"
}return e.join("")},addPagerBehavior:function(){var b=this;if(!b.pager.pages){return}var c=b.pager.currentPage;var a=b.pager.pages;var d=b.pager.total;if(d>0){if(c>1){$("mtgFirst"+this.mtgId).down("img").src=b.imageRefs.firstIcon;
$("mtgFirst"+this.mtgId).onclick=function(){b.retrieveDataFromUrl.call(b,1)}}else{$("mtgFirst"+this.mtgId).down("img").src=b.imageRefs.firstDisabledIcon}if(c>0&&c<a){$("mtgNext"+this.mtgId).down("img").src=b.imageRefs.nextIcon;
$("mtgNext"+this.mtgId).onclick=function(){b.retrieveDataFromUrl.call(b,c+1)}}else{$("mtgNext"+this.mtgId).down("img").src=b.imageRefs.nextDisabledIcon}if(c>1&&c<=a){$("mtgPrev"+this.mtgId).down("img").src=b.imageRefs.prevIcon;
$("mtgPrev"+this.mtgId).onclick=function(){b.retrieveDataFromUrl.call(b,c-1)}}else{$("mtgPrev"+this.mtgId).down("img").src=b.imageRefs.prevDisabledIcon}if(c<a){$("mtgLast"+this.mtgId).down("img").src=b.imageRefs.lastIcon;
$("mtgLast"+this.mtgId).onclick=function(){b.retrieveDataFromUrl.call(b,b.pager.pages)}}else{$("mtgLast"+this.mtgId).down("img").src=b.imageRefs.lastDisabledIcon}var e=function(g){if(g.keyCode==Event.KEY_RETURN){var f=$("mtgPageInput"+b.mtgId).value;
if(f>a){f=a}if(f<1){f="1"}$("mtgPageInput"+b.mtgId).value=f;b.retrieveDataFromUrl.call(b,f)}};if(Prototype.Browser.Gecko||Prototype.Browser.Opera){Event.observe($("mtgPageInput"+this.mtgId),"keypress",function(f){e(f)
})}else{Event.observe($("mtgPageInput"+this.mtgId),"keydown",function(f){e(f)})}}},resize:function(){var c=$(this.target);var b=this.options.width||(c.getWidth()-this.fullPadding(c,"left")-this.fullPadding(c,"right"))+"px";
var a=this.options.height||(c.getHeight()-this.fullPadding(c,"top")-this.fullPadding(c,"bottom"))+"px";this.tableWidth=parseInt(b)-2;this.tableHeight=parseInt(a)-2;this.tableDiv.setStyle({width:this.tableWidth+"px",height:this.tableHeight+"px"});
if(this.options.title){$("mtgHeaderTitle"+this.mtgId).setStyle({width:(this.tableWidth-6)+"px"})}this.headerRowDiv.setStyle({width:(this.tableWidth)+"px"});this.bodyHeight=this.tableHeight-this.headerHeight-3;
if(this.options.title){this.bodyHeight=this.bodyHeight-this.headerHeight-1}if(this.options.pager){this.bodyHeight=this.bodyHeight-this.pagerHeight}this.bodyDiv.setStyle({width:(this.tableWidth)+"px",height:this.bodyHeight+"px"});
if(this.options.pager){this.pagerDiv.setStyle({width:(this.tableWidth-2)+"px"})}},getValueAt:function(a,b){a=this.getColumnIndex(this.columnModel[a].id);return this.rows[b][a]},setValueAt:function(b,a,c){a=this.getColumnIndex(this.columnModel[a].id);
this.rows[c][a]=b},getColumnIndex:function(c){var a=-1;for(var b=0;b<this.columnModel.length;b++){if(this.columnModel[b].id==c){a=this.columnModel[b].positionIndex;break}}return a},getIndexOf:function(b){var a=0;
for(;a<this.columnModel.length;a++){if(this.columnModel[a].id==b){break}}return a},getCurrentPosition:function(){return[this.keys.xOldPos,this.keys.yOldPos]},getCellElementAt:function(a,b){return $("mtgC"+this.mtgId+"_"+a+","+b)
},getModifiedRows:function(){var b=[];for(var d=0;d<this.modifiedRows.length;d++){var a=this.modifiedRows[d];var e={};for(var c=0;c<this.columnModel.length;c++){e[this.columnModel[c].id]=this.rows[a][this.columnModel[c].positionIndex]
}b.push(e)}return b},highlightRow:function(e,c){$$(".mtgRow"+this.mtgId).each(function(f){f.removeClassName("focus")});var a=this.getColumnIndex(e);var d=-1;for(var b=0;b<this.rows.length;b++){if(this.rows[b][a]==c){d=b;
break}}if(d>=0){$("mtgRow"+this.mtgId+"_"+d).addClassName("focus")}},getRow:function(c){var a={};for(var b=0;b<this.columnModel.length;b++){a[this.columnModel[b].id]=this.rows[c][this.columnModel[b].positionIndex]
}return a},clear:function(){this.modifiedRows=[]}};MyTableGrid.CellAutocompleter=Class.create({initialize:function(a){a=a||{};this.url=a.url||null;this.divListId=a.divListId||"list";this.list=a.list||[];
this.afterUpdateCallback=a.afterUpdate||null;this.getParameters=a.getParameters||null;this.listTextPropertyName=a.listTextPropertyName||"text";this.listValuePropertyName=a.listValuePropertyName||"value"
},render:function(d,c){var h=d.getCurrentPosition();var b=new Element("input",{id:"mtgInput"+d.mtgId+"_"+h[0]+","+h[1],type:"text",value:c.value});var g=(Prototype.Browser.IE)?"1px":"2px";b.addClassName("mtgInputText");
b.addClassName("mtgComboBox");b.setStyle({width:(c.width-9)+"px",height:(c.height-10)+"px",paddingLeft:"3px",paddingRight:"3px",marginTop:g,marginLeft:"1px"});var e={};var a=this;e.afterUpdateElement=function(i,j){d.setValueAt(j.id,h[0],h[1]);
if(a.afterUpdateCallback){a.afterUpdateCallback(i,j)}};e.listTextPropertyName=this.listTextPropertyName;e.listValuePropertyName=this.listValuePropertyName;if(this.url){var f={};if(this.getParameters){f=this.getParameters()
}new Ajax.Request(this.url,{parameters:f,onSuccess:function(j){var i=j.responseText.evalJSON();new Autocompleter.CellElement(b,a.divListId,i,e)}})}else{new Autocompleter.CellElement(b,this.divListId,this.list,e)
}return b}});MyTableGrid.CellCheckbox=Class.create({initialize:function(a){a=a||{};this.onClickCallback=a.onClick||null}});MyTableGrid.CellRadioButton=Class.create({initialize:function(a){a=a||{};this.onClickCallback=a.onClick||null
}});MyTableGrid.BrowseInput=Class.create({initialize:function(a){a=a||{};this.afterUpdate=a.afterUpdate||null;this.onClick=a.onClick||null},render:function(f,k){var e=f.getCurrentPosition();var i=new Element("span");
var g=new Element("input",{id:"mtgInput"+f.mtgId+"_"+e[0]+","+e[1],type:"text",value:k.value});var b=(Prototype.Browser.IE)?"1px":"2px";g.addClassName("mtgInputText");g.setStyle({width:(k.width-30)+"px",height:(k.height-10)+"px",paddingLeft:"3px",paddingRight:"3px",marginTop:b,marginLeft:"1px",textAlign:k.align});
i.appendChild(g);var h=new Element("a",{href:"#"});var d=false;h.onclick=function(){j.onClick();d=true};var c=new Element("img",{id:"mtgMagnifierBtn"+f.mtgId,src:f.imageRefs.mtgMagnifierIcon,width:"16",height:"16",border:"0"});
h.appendChild(c);i.appendChild(h);var j=this;this.afterUpdateCallback=function(a,l){f.setValueAt(l,e[0],e[1]);if(j.afterUpdate&&!d){j.afterUpdate(a,l)}d=false};return i}});Autocompleter.CellElement=Class.create(Autocompleter.Base,{initialize:function(b,d,c,a){this.baseInitialize(b,d,a);
this.options.array=c;this.listTextPropertyName=a.listTextPropertyName||"text";this.listValuePropertyName=a.listValuePropertyName||"value"},getUpdatedChoices:function(){this.updateChoices(this.options.selector(this))
},setOptions:function(a){this.options=Object.extend({choices:10,partialSearch:true,partialChars:1,ignoreCase:true,fullSearch:false,selector:function(b){var d=[];var c=[];var g=b.getToken();var f="";var h="";
var e=0;if(b.keyPressed==Event.KEY_DOWN&&!b.active){for(e=0;e<b.options.array.length;e++){f=b.options.array[e][b.listTextPropertyName];h=b.options.array[e][b.listValuePropertyName];d.push('<li id="'+h+'">'+f+"</li>")
}}else{for(e=0;e<b.options.array.length&&d.length<b.options.choices;e++){f=b.options.array[e][b.listTextPropertyName];h=b.options.array[e][b.listValuePropertyName];var j=b.options.ignoreCase?f.toLowerCase().indexOf(g.toLowerCase()):f.indexOf(g);
while(j!=-1){if(j==0&&f.length!=g.length){d.push('<li id="'+h+'"><strong>'+f.substr(0,g.length)+"</strong>"+f.substr(g.length)+"</li>");break}else{if(g.length>=b.options.partialChars&&b.options.partialSearch&&j!=-1){if(b.options.fullSearch||/\s/.test(f.substr(j-1,1))){c.push("<li>"+f.substr(0,j)+"<strong>"+f.substr(j,g.length)+"</strong>"+f.substr(j+g.length)+"</li>");
break}}}j=b.options.ignoreCase?f.toLowerCase().indexOf(g.toLowerCase(),j+1):f.indexOf(g,j+1)}}}if(c.length){d=d.concat(c.slice(0,b.options.choices-d.length))}return"<ul>"+d.join("")+"</ul>"}},a||{})}});