$Comp.ProgressBar=Class.create({initialize:function(a,c){this.options={afterChange:Prototype.emptyFunction,interval:1,maxProgressValue:100,url:"",startAfterCreate:true,showAbortAction:true,showDetailAction:true,detailHeight:"120px",height:17};
Object.extend(this.options,c||{});a=$(a);a.setDimensions(this.options);this.step=this.options.step||0;this.showMenu=this.options.showAbortAction||this.options.showDetailAction;this.menuWidth=this.showMenu?10:0;
var e=new Element("div",{className:"bg",style:"right:"+this.menuWidth+"px"});var f=new Element("div",{className:"pb_text",style:"line-height:"+(a.getHeight()-1)+"px"}).update("0%");this.progress=new Element("div",{className:"progressbar"}).insert(e).insert(f);
a.update(this.progress);var b=[];if(this.options.showAbortAction){b.push({name:$MessageConst["Progressbar.0"],onSelect:this._abortAction.bind(this)})}if(this.options.showDetailAction){b.push({name:$MessageConst["Progressbar.1"],onSelect:this._detailAction.bind(this)})
}if(b.length>0){var d=new Element("div",{className:"btn"}).update("&nbsp;");this.progress.insert(d);new $Comp.Menu(null,{selector:"#"+d.identify(),menuEvent:"click",minWidth:"100px",menuItems:b})}e.setStyle("width:"+this._getBackgroundWidth()+"px");
if(this.step>0){this.setProgress(this.step)}if(this.options.startAfterCreate){this.start()}},_abortAction:function(a,b){},_detailAction:function(b,c){var a=this.progress.next(".progressbar_detail");if(!a){a=new Element("div",{className:"progressbar_detail",style:"display:none"}).insert(new Element("div",{className:"menu"})).insert(new Element("div",{className:"content",style:"height:"+this.options.detailHeight}));
this.progress.insert({after:a});this._createDetailMenu(a)}a.$show2({effects:this.options.effects})},_createDetailMenu:function(b){var c=b.down(".content");var a=[{name:$MessageConst["Progressbar.2"],onSelect:function(d,f){this._removeMessages(c)
}.bind(this)},{name:$MessageConst["Progressbar.3"],onSelect:function(f,g){var d=this.options.url;d=d.addParameter("messages=true");new Ajax.Request(d,{onComplete:function(h){var e=h.responseText.evalJSON();
if(e){this._removeMessages(c);$A(e).each(function(i){this._updateMessage(c,i)}.bind(this))}}.bind(this)})}.bind(this)},{name:$MessageConst["Progressbar.4"],checkbox:true,checked:this.noScroll,onCheck:function(d,f){this.noScroll=!d.isItemChecked();
d.setItemChecked(this.noScroll)}.bind(this)},{separator:true},{name:$MessageConst["Progressbar.5"],onSelect:function(d,f){b.$remove({effects:this.options.effects})}.bind(this)}];new $Comp.Menu(null,{selector:"#"+b.down(".menu").identify(),menuEvent:"click",minWidth:"150px",menuItems:a})
},_ajaxComplete:function(b){var a=b.responseText.evalJSON();if(!a){this.stop();return}if(a.abort){this.stop();return}if(a.maxProgressValue>0){this.options.maxProgressValue=a.maxProgressValue}this.setProgress(a.step,function(){var c=this.progress.next(".progressbar_detail");
if(c&&a.message){this._updateMessage(c.down(".content"),a.message)}}.bind(this))},_removeMessages:function(a){a.select(".msg").invoke("remove");a.scrollTop=0},_updateMessage:function(b,a){b.insert(new Element("div",{className:"msg m1"}).update(a));
if(!this.noScroll){b.scrollTop=b.scrollHeight}},_getBackgroundWidth:function(){return this.progress.getWidth()-this.menuWidth-2},updateUI:function(){this._draw()},_draw:function(){if(this.drawing){return
}var a=this._getBackgroundWidth();var c=this.progress.down(".bg");a=a-Math.floor((this.step/this.options.maxProgressValue)*a);c.$style("width:"+a+"px",{effects:this.options.effects,afterFinish:function(d){this.drawing=false
}.bind(this)});var b=Math.round((this.step/this.options.maxProgressValue)*10000)/100;c.setStyle("border-left-width: "+(b<100?1:0)+"px;");this.progress.down(".pb_text").update(b+"%")},setProgress:function(a,b){if(!this.progress.descendantOf(document)){this.stop()
}else{this.step=a||0;if(this.step>this.options.maxProgressValue){this.stop()}this._draw();$eval(b)}},start:function(){this.starting=true;if(!this.executer){this.executer=new PeriodicalExecuter(function(){var a=this.options.url;
if(this.starting){a=a.addParameter("starting=true");this.starting=false}new Ajax.Request(a,{onComplete:this._ajaxComplete.bind(this)})}.bind(this),this.options.interval)}},isStop:function(){return !this.executer||!this.executer.timer
},stop:function(){if(this.executer){this.executer.stop()}}});function __progressbar_actions_init(a){a.start=function(){a.progressbar.start()};a.stop=function(){a.progressbar.stop()};a.updateUI=function(){a.progressbar.updateUI()
}};