$Comp.Slider=Class.create({sliders:[],_bar:null,_arrow:null,initialize:function(c,a){this.id=c;this.settings={xMinValue:0,xMaxValue:100,yMinValue:0,yMaxValue:100,arrowImage:""};Object.extend(this.settings,a||{});
this.xValue=0;this.yValue=0;this._bar=$(this.id);this._bar.setDimensions(this.settings);this._bar.addClassName("slider_bar");this._arrow=new Element("img",{src:this.settings.arrowImage,className:"slider_img"});
this._bar.insert({after:this._arrow});this._arrow.observeImageLoad(function(){this.setArrowPositionFromValues()}.bind(this));Event.observe(window,"resize",function(){this.setArrowPositionFromValues()}.bind(this));
this.setArrowPositionFromValues();var b=this;this._event_docMouseMove=this._docMouseMove.bindAsEventListener(this);this._event_docMouseUp=this._docMouseUp.bindAsEventListener(this);Event.observe(this._bar,"mousedown",this._bar_mouseDown.bindAsEventListener(this));
Event.observe(this._arrow,"mousedown",this._arrow_mouseDown.bindAsEventListener(this));if(this.onValuesChanged){this.onValuesChanged(this)}this.sliders.push(this)},setPositioningVariables:function(){this._barWidth=this._bar.getWidth();
this._barHeight=this._bar.getHeight();var a=this._bar.positionedOffset();this._barTop=a.top;this._barLeft=a.left;this._barBottom=this._barTop+this._barHeight;this._barRight=this._barLeft+this._barWidth;
this._arrow=$(this._arrow);this._arrowWidth=this._arrow.getWidth();this._arrowHeight=this._arrow.getHeight();this.MinX=this._barLeft;this.MinY=this._barTop;this.MaxX=this._barRight;this.MinY=this._barBottom
},setArrowPositionFromValues:function(g){this.setPositioningVariables();var b=0;var a=0;if(this.settings.xMinValue!=this.settings.xMaxValue){if(this.xValue==this.settings.xMinValue){b=0}else{if(this.xValue==this.settings.xMaxValue){b=this._barWidth-1
}else{var h=this.settings.xMaxValue;if(this.settings.xMinValue<1){h=h+Math.abs(this.settings.xMinValue)+1}var d=this.xValue;if(this.xValue<1){d=d+1}b=d/h*this._barWidth;if(parseInt(b)==(h-1)){b=h}else{b=parseInt(b)
}if(this.settings.xMinValue<1){b=b-Math.abs(this.settings.xMinValue)-1}}}}if(this.settings.yMinValue!=this.settings.yMaxValue){if(this.yValue==this.settings.yMinValue){a=0}else{if(this.yValue==this.settings.yMaxValue){a=this._barHeight-1
}else{var f=this.settings.yMaxValue;if(this.settings.yMinValue<1){f=f+Math.abs(this.settings.yMinValue)+1}var c=this.yValue;if(this.yValue<1){c=c+1}var a=c/f*this._barHeight;if(parseInt(a)==(f-1)){a=f}else{a=parseInt(a)
}if(this.settings.yMinValue<1){a=a-Math.abs(this.settings.yMinValue)-1}}}}this._setArrowPosition(b,a)},_setArrowPosition:function(a,d){if(a<0){a=0}if(a>this._barWidth){a=this._barWidth}if(d<0){d=0}if(d>this._barHeight){d=this._barHeight
}var c=this._barLeft+a;var b=this._barTop+d;if(this._arrowWidth>this._barWidth){c=c-(this._arrowWidth/2-this._barWidth/2)}else{c=c-parseInt(this._arrowWidth/2)}if(this._arrowHeight>this._barHeight){b=b-(this._arrowHeight/2-this._barHeight/2)
}else{b=b-parseInt(this._arrowHeight/2)}this._arrow.style.left=(c+this._bar.measure("margin-left"))+"px";this._arrow.style.top=(b+this._bar.measure("margin-top"))+"px"},_bar_mouseDown:function(a){this._mouseDown(a)
},_arrow_mouseDown:function(a){this._mouseDown(a)},_mouseDown:function(a){$Comp.ActiveSlider=this;this.setValuesFromMousePosition(a);Event.observe(document,"mousemove",this._event_docMouseMove);Event.observe(document,"mouseup",this._event_docMouseUp);
Event.stop(a)},_docMouseMove:function(a){this.setValuesFromMousePosition(a);Event.stop(a)},_docMouseUp:function(a){Event.stopObserving(document,"mouseup",this._event_docMouseUp);Event.stopObserving(document,"mousemove",this._event_docMouseMove);
Event.stop(a)},setValuesFromMousePosition:function(c){var f=Event.pointer(c);var g=this._bar.cumulativeOffset();var h=this._bar.positionedOffset();var k=f.x-g.left+h.left;var j=f.y-g.top+h.top;var d=0;
var b=0;if(k<this._barLeft){d=0}else{if(k>this._barRight){d=this._barWidth}else{d=k-this._barLeft+1}}if(j<this._barTop){b=0}else{if(j>this._barBottom){b=this._barHeight}else{b=j-this._barTop+1}}var a=parseInt(d/this._barWidth*this.settings.xMaxValue);
var i=parseInt(b/this._barHeight*this.settings.yMaxValue);this.xValue=a;this.yValue=i;if(this.settings.xMaxValue==this.settings.xMinValue){d=0}if(this.settings.yMaxValue==this.settings.yMinValue){b=0}this._setArrowPosition(d,b);
if(this.onValuesChanged){this.onValuesChanged(this)}}});