var MENU_DOCUMENT_CLICK=false;$Comp.Menu=Class.create({shown:[],initialize:function(a,b){this.options={zIndex:900,pageOffset:25,topOffset:-1,onBeforeShow:null,menuEvent:null};this.setOptions(b);if(a){this.element=$(a);
this.element.setDimensions(this.options);this.createMainList(this.options.menuItems)}else{this.element=this.createMenu(document.body,this.options.menuItems);this.bindEvent(this.options.selector)}if(!MENU_DOCUMENT_CLICK){document.observe("click",function(c){if(!c.isRightClick()){this.hideAll(c)
}}.bind(this));MENU_DOCUMENT_CLICK=true}},setOptions:function(a){Object.extend(this.options,a||{})},_eventHandle:function(a){if(a){a.stop()}this.hideAll(a);this.show(a,this.element)},bindEvent:function(a,b){if(!a){return
}$elements(a).invoke("observe",(b||this.options.menuEvent),this._eventHandle.bind(this))},show:function(b,c,d){if(c.visible()){return}if(!d){c.targetObject=Event.element(b)}if(this.options.onBeforeShow){if(this.options.onBeforeShow(c,b)==false){return
}}var a=this.position(b,c,d);c.setStyle({left:a.left+"px",top:a.top+"px",zIndex:this.options.zIndex});c.$show({effects:this.options.effects})},hide:function(a){a.$hide({effects:this.options.effects})},hideAll:function(a){this.shown.each(function(b){if(b.mi){b.mi.removeClassName("active")
}b.hide()}.bind(this))},createMainList:function(a){a.each(function(c){var b;if(c.separator){b=$Comp.createLink(null,{className:"ms"})}else{b=$Comp.createLink(c.name,{className:c.disabled?"mm disabled":"mm",title:(c.desc||""),href:c.url?c.url:null});
this.createItemFunction(b);if(!c.url&&c.onSelect){b.observe("click",function(d){if(!b.isItemDisabled()){c.onSelect(b,d)}else{Event.stop(d)}})}}var e;if(c.submenu){e=this.createMenu(document.body,c.submenu)
}b.observe("mouseover",(function(d){this.hideAll(d);if(e){e.mi=b;b.addClassName("active");this.show(d,e)}}).bind(this));this.element.insert(b)}.bind(this));this.element.insert(new Element("div",{style:"clear:both;"}))
},createItemFunction:function(b){b.isItemDisabled=function(){return b.hasClassName("disabled")};b.setItemDisabled=function(a){if(a){b.addClassName("disabled")}else{b.removeClassName("disabled")}};b.isItemChecked=function(){return b.up().hasClassName("checked")
};b.setItemChecked=function(c){var a=b.up();a.removeClassName(c?"unchecked":"checked");a.addClassName(c?"checked":"unchecked")};b.setText=function(a){b.update(a)};b.setItemVisible=function(c){var a=b.up("li");
if(c){a.show()}else{a.hide()}};b.hideMenu=function(){var a=b.getMenu();while(a){this.hide(a);a=a.getParentMenu()}}.bind(this);b.getMenu=function(){return b.up(".menu")};b.getSubMenu=function(){return b.down(".menu")
};b.getTargetObject=function(){return b.getMenu().getTargetObject()}.bind(this)},createMenuFunction:function(a){a.firstLevel=function(){return(a.up()==document.body)};a.getRootMenu=function(){var b=a;while(!b.firstLevel()){b=b.getParentMenu()
}return b};a.getParentMenu=function(){return a.up(".menu")};a.getItems=function(){var b=[];a.down("ul").immediateDescendants().each(function(c){var d=c.down("a");if(d){b.push(d)}});return b};a.getTargetObject=function(){return a.getRootMenu().targetObject
}},createList:function(a){var b=new Element("ul");a.each(function(f){var c=new Element("li",{className:f.separator?"separator":""});b.insert(c);if(f.separator){c.insert("&nbsp;")}else{var e=$Comp.createLink(f.name,{className:(f.disabled?"disabled":"")+(f.submenu?" submenu":""),title:(f.desc||""),href:f.url?f.url:null});
e.observe("contextmenu",Event.stop);if(f.submenu){this.createMenu(e,f.submenu)}this.createItemFunction(e);if(!f.url&&f.onSelect){e.observe("click",function(g){if(!e.isItemDisabled()){e.hideMenu();f.onSelect(e,g)
}else{if(!f.checkbox){Event.stop(g)}}})}var d=e;if(f.checkbox){d=d.wrap({className:f.checked?"checked":"unchecked"});d.observe("click",function(g){if(f.onCheck){f.onCheck(e,g)}else{e.setItemChecked(!e.isItemChecked())
}Event.stop(g)})}else{if(f.icon){d=d.wrap({className:"icon",style:"background-image:url("+f.icon+")"})}}if(f.submenu){d=d.wrap({className:"more"})}c.insert(d)}}.bind(this));return b},createMenu:function(b,a){b=$(b);
var c=this.createList(a).wrap({className:"menu desktop",style:"display:none"}).observe("contextmenu",Event.stop);if(this.options.minWidth){c.setStyle(((Browser.IEVersion&&Browser.IEVersion<=6)?"width:":"min-width:")+this.options.minWidth)
}b.insert(c);this.createMenuFunction(c);c.getItems().each(function(e){var d=e.getSubMenu();if(!d){return}e.observe("mouseover",function(f){this.show(f,d,true)}.bind(this));e.observe("mouseout",function(f){if(f.relatedTarget.descendantOf(e)){return
}this.hide(d)}.bind(this))}.bind(this));this.shown.push(c);return c},position:function(l,d,b){var q,m;var f=b?d.up(".menu"):d.targetObject;if(b){var g=f.cumulativeOffset();var k=f.cumulativeScrollOffset();
q=(g.left-k.left)+f.getWidth()}else{if(this.options.menuEvent=="contextmenu"){var c=Event.pointer(l);q=c.x;m=c.y}else{var g=f.cumulativeOffset();var k=f.cumulativeScrollOffset();q=g.left-k.left;var i=f.getDimensions().height;
m=(g.top-k.top)+i+this.options.topOffset}}var n=document.viewport.getScrollOffsets();if(this.options.menuEvent!="contextmenu"){m+=n.top;q+=n.left}var a=document.viewport.getDimensions();var j=d.getDimensions();
var t=(q+j.width+this.options.pageOffset)>a.width?(a.width-j.width-this.options.pageOffset):q;var s=m?((m-n.top+j.height)>a.height&&(m-n.top)>j.height?(m-j.height):m):-2;if(b){t=(f.getWidth()-10)-(q-t)
}return Object.clone(Object.extend(j,{left:t,top:s}))}});$target=function(a){a=$(a);return a.getTargetObject?a.getTargetObject():a};function __menu_actions_init(a){a.bindEvent=function(b){a.menu.bindEvent(b)
}};