Date.weekdays=$w($MessageConst["Calendar.0"]);Date.months=$w("1 2 3 4 5 6 7 8 9 10 11 12");Date.first_day_of_week=0;Element.addMethods({build:function(c,e,a,d){var f=new Element(e);$H(a).each(function(g){f[g.key]=g.value
});if(d){f.setStyle(d)}c.appendChild(f);return f}});Date.one_day=24*60*60*1000;Date.padded2=function(a){var c=parseInt(a,10);if(a<10){c="0"+c}return c};Date.prototype.stripTime=function(){return new Date(this.getFullYear(),this.getMonth(),this.getDate())
};Date.prototype.daysDistance=function(a){return Math.round((a-this)/Date.one_day)};Math.floor_to_interval=function(c,a){return Math.floor(c/a)*a};SelectBox=Class.create({initialize:function(e,c,d,a){this.element=$(e).build("select",d,a);
this.populate(c)},populate:function(a){this.element.update("");var c=this;$A(a).each(function(d){if(typeof(d)!="object"){d=[d,d]}c.element.build("option",{value:d[1],innerHTML:d[0]})})},setValue:function(c){var d=this.element;
var a=false;$R(0,d.options.length-1).each(function(e){if(d.options[e].value==c.toString()){d.selectedIndex=e;a=true}});return a},getValue:function(){return $F(this.element)}});CalendarDateSelect=Class.create();
CalendarDateSelect.prototype={initialize:function(a){this.options={dateFormat:"yyyy-MM-dd",showTime:false,clearButton:true,yearRange:100,minuteInterval:1,embedded:null,onclose:null,onchange:null,oncheck:null};
Object.extend(this.options,a||{})},show:function(c,a){this.inputField=$(c);if(this.inputField&&this.inputField.tagName!="INPUT"){this.inputField=this.inputField.down("INPUT")}if(!this.inputField){return
}if(a){this.options.dateFormat=a}this.inputField.calendar_date_select=this;this.parseDate();this.initCalendarDiv();var d=$(this.options.embedded);if(!d){Event.observe(document,"mousedown",this.closeIfClickedOut_handler=this.closeIfClickedOut.bindAsEventListener(this));
Event.observe(document,"keypress",this.keyPress_handler=this.keyPress.bindAsEventListener(this));var e=$Comp.getPopup(this.calendar_div);this.calendar_div.style.left=e[0]+"px";this.calendar_div.style.top=e[1]+"px"
}this.calendar_div.$show({effects:this.options.effects})},initCalendarDiv:function(){if(!this.calendar_div){var embedded=$(this.options.embedded);this.calendar_div=Element.build(embedded?embedded:document.body,"div",{className:"calendar_date_select"},embedded?{}:{position:"absolute"}).hide();
this.calendar_div.createDrag();var that=this;$w("top header body buttons footer bottom").each(function(name){eval("var "+name+"_div = that."+name+"_div = that.calendar_div.build('div', { className: 'cds_"+name+"' }, { clear: 'left'} ); ")
});this.initHeaderDiv();this.initButtonsDiv();this.initCalendarGrid()}this.refresh();this.setUseTime()},initHeaderDiv:function(){var a=this.header_div;this.next_month_button=a.build("a",{href:"###",onclick:function(){this.navMonth(this.date.getMonth()+1);
return false}.bindAsEventListener(this),className:"next"});this.prev_month_button=a.build("a",{href:"###",onclick:function(){this.navMonth(this.date.getMonth()-1);return false}.bindAsEventListener(this),className:"prev"});
this.year_select=new SelectBox(a,[],{className:"year",onchange:function(){this.navYear(this.year_select.getValue())}.bindAsEventListener(this)});this.populateYearRange();this.month_select=new SelectBox(a,$R(0,11).map(function(c){return[Date.months[c],c]
}),{className:"month",onchange:function(){this.navMonth(this.month_select.getValue())}.bindAsEventListener(this)})},initCalendarGrid:function(){var a=this.body_div;this.calendar_day_grid=[];var h=a.build("table",{cellPadding:"0px",cellSpacing:"0px",width:"100%"});
var c=h.build("thead").build("tr");Date.weekdays.each(function(i){c.build("th",{innerHTML:i})});var f=h.build("tbody");var d=0,e;for(var g=0;g<42;g++){e=(g+Date.first_day_of_week)%7;if(g%7==0){days_row=f.build("tr",{className:"row_"+d++})
}(this.calendar_day_grid[g]=days_row.build("td",{calendar_date_select:this,onmouseover:function(){this.calendar_date_select.dayHover(this)},onmouseout:function(){this.calendar_date_select.dayHoverOut(this)
},onclick:function(){this.calendar_date_select.updateSelectedDate(this,true)},className:(e==0)||(e==6)?" weekend":""},{cursor:"pointer"}))}},initButtonsDiv:function(){var d=this.buttons_div;if(this.options.showTime){var a=[];
d.build("span",{className:"at_sign"});this.hour_select=new SelectBox(d,a.concat($R(0,23).map(function(e){return $A([e,e])})),{calendar_date_select:this,onchange:function(){this.calendar_date_select.updateSelectedDate({hour:this.value});
this.calendar_date_select.updateFooter()},className:"hour"});d.build("span",{innerHTML:":",className:"seperator"});var c=this;this.minute_select=new SelectBox(d,a.concat($R(0,59).select(function(e){return(e%c.options.minuteInterval==0)
}).map(function(e){return $A([Date.padded2(e),e])})),{calendar_date_select:this,onchange:function(){this.calendar_date_select.updateSelectedDate({minute:this.value});this.calendar_date_select.updateFooter()
},className:"minute"});d.build("br")}d.build("span",{innerHTML:"&nbsp;"});b=d.build("a",{innerHTML:$MessageConst["Calendar.1"],href:"###",onclick:function(){this.today();return false}.bindAsEventListener(this)});
if(this.options.clearButton){d.build("span",{innerHTML:"&nbsp;|&nbsp;",className:"button_seperator"});d.build("a",{innerHTML:$MessageConst["Calendar.2"],href:"###",onclick:function(){this.clearDate();if(!this.embedded){this.close()
}return false}.bindAsEventListener(this)})}},refresh:function(){this.refreshMonthYear();this.refreshCalendarGrid();this.setSelectedClass();this.updateFooter()},refreshCalendarGrid:function(){this.beginning_date=new Date(this.date).stripTime();
this.beginning_date.setDate(1);this.beginning_date.setHours(12);var c=this.beginning_date.getDay();if(c<3){c+=7}this.beginning_date.setDate(1-c+Date.first_day_of_week);var e=new Date(this.beginning_date);
var a=new Date().stripTime();var d=this.date.getMonth();vdc=this.options.oncheck;for(var f=0;f<42;f++){day=e.getDate();month=e.getMonth();cell=this.calendar_day_grid[f];cell.innerHTML=day;if(month!=d){cell.addClassName("other")
}else{cell.removeClassName("other")}cell.day=day;cell.month=month;cell.year=e.getFullYear();if(vdc){if(vdc(e.stripTime())){cell.removeClassName("disabled")}else{cell.addClassName("disabled")}}e.setDate(day+1)
}if(this.today_cell){this.today_cell.removeClassName("today")}if($R(0,41).include(days_until=this.beginning_date.stripTime().daysDistance(a))){this.today_cell=this.calendar_day_grid[days_until];this.today_cell.addClassName("today")
}},refreshMonthYear:function(){var a=this.date.getMonth();var d=this.date.getFullYear();this.month_select.setValue(a,false);var c=this.year_select.element;if(this.flexibleYearRange()&&(!(this.year_select.setValue(d,false))||c.selectedIndex<=1||c.selectedIndex>=c.options.length-2)){this.populateYearRange()
}this.year_select.setValue(d)},populateYearRange:function(){this.year_select.populate(this.yearRange().toArray())},yearRange:function(){if(!this.flexibleYearRange()){return $R(this.options.yearRange[0],this.options.yearRange[1])
}var a=this.date.getFullYear();return $R(a-this.options.yearRange,a+this.options.yearRange)},flexibleYearRange:function(){return(typeof(this.options.yearRange)=="number")},validYear:function(a){if(this.flexibleYearRange()){return true
}else{return this.yearRange().include(a)}},dayHover:function(a){var c=new Date(this.selected_date);c.setYear(a.year);c.setMonth(a.month);c.setDate(a.day);this.updateFooter(c.format(this.options.dateFormat))
},dayHoverOut:function(a){this.updateFooter()},clearSelectedClass:function(){if(this.selected_cell){this.selected_cell.removeClassName("selected")}},setSelectedClass:function(){if(!this.selection_made){return
}this.clearSelectedClass();if($R(0,42).include(days_until=this.beginning_date.stripTime().daysDistance(this.selected_date.stripTime()))){this.selected_cell=this.calendar_day_grid[days_until];this.selected_cell.addClassName("selected")
}},reparse:function(){this.parseDate();this.refresh()},dateString:function(){return(this.selection_made)?this.selected_date.format(this.options.dateFormat):"&nbsp;"},parseDate:function(){var a=$F(this.inputField).strip();
this.selection_made=(a!="");this.date=Date.parseString(this.options.date||a,this.options.dateFormat);if(!this.date){this.date=new Date()}if(!this.validYear(this.date.getFullYear())){this.date.setYear((this.date.getFullYear()<this.yearRange().start)?this.yearRange().start:this.yearRange().end)
}this.selected_date=new Date(this.date)},updateFooter:function(a){if(!a){a=this.dateString()}this.footer_div.update("");this.footer_div.build("span",{innerHTML:a})},clearDate:function(){var a=this.inputField.value;
this.inputField.value="";this.clearSelectedClass();this.updateFooter("&nbsp;");if(a!=this.inputField.value){this.callback("onchange")}},updateSelectedDate:function(d,c){var g=$H(d);if(g.get("day")){var f=this.selected_date,e=this.options.oncheck;
for(var a=0;a<=3;a++){f.setDate(g.get("day"))}f.setYear(g.get("year"));f.setMonth(g.get("month"));if(e&&!e(f.stripTime())){return false}this.selected_date=f;this.selection_made=true}if(!isNaN(g.get("hour"))){this.selected_date.setHours(g.get("hour"))
}if(!isNaN(g.get("minute"))){this.selected_date.setMinutes(Math.floor_to_interval(g.get("minute"),this.options.minuteInterval))}if(this.selection_made){this.updateValue()}if(c&&this.closeOnClick(this)){this.close()
}},closeOnClick:function(){if(this.embedded){return false}if(this.options.onclose===null){return true}else{return(this.options.onclose)}},navMonth:function(a){(target_date=new Date(this.date)).setMonth(a);
return(this.navTo(target_date))},navYear:function(a){(target_date=new Date(this.date)).setYear(a);return(this.navTo(target_date))},navTo:function(a){if(!this.validYear(a.getFullYear())){return false}this.date=a;
this.updateSelectedDate({day:a.getDate(),month:a.getMonth(),year:a.getFullYear()},false);this.refresh();this.callback("after_navigate",this.date);return true},setUseTime:function(){if(this.options.showTime&&this.selected_date){var c=Math.floor_to_interval(this.selected_date.getMinutes(),this.options.minuteInterval);
var a=this.selected_date.getHours();this.hour_select.setValue(a);this.minute_select.setValue(c)}},updateValue:function(){var a=this.inputField.value;this.inputField.value=this.dateString();if(a!=this.inputField.value){this.callback("onchange")
}},today:function(){var a=new Date();this.date=a;this.updateSelectedDate({day:a.getDate(),month:a.getMonth(),year:a.getFullYear(),hour:a.getHours(),minute:a.getMinutes()},false);this.refresh()},close:function(){Event.stopObserving(document,"mousedown",this.closeIfClickedOut_handler);
Event.stopObserving(document,"keypress",this.keyPress_handler);this.inputField.calendar_date_select=null;this.calendar_div.$hide({effects:this.options.effects});try{this.inputField.focus()}catch(a){}},closeIfClickedOut:function(a){if(!$(Event.element(a)).descendantOf(this.calendar_div)){this.close()
}},keyPress:function(a){if(a.keyCode==Event.KEY_ESC){this.close()}},callback:function(a,c){if(this.options[a]){this.options[a].bind(this.inputField)(c)}}};